import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownRight, ArrowUpRight, Check, Menu, Search, X } from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Link, Route, Switch, Router as WouterRouter } from 'wouter';
import logoAsset from '@assets/IMG_1920_1786731585196.png';

const queryClient = new QueryClient();
const logo = logoAsset;
const INSTAGRAM = 'https://www.instagram.com/majangmejeng_/';
const TIKTOK = 'https://www.tiktok.com/@majangmejeng_?lang=id-ID';

type Story = { slug: string; category: string; title: string; dek: string; image: string; platform: string; read: string };
const stories: Story[] = [
  { slug: 'pasar-santa-dan-kota-yang-mendengar', category: 'Kota', title: 'Di balik riuhnya pasar, ada kota yang sedang belajar mendengar', dek: 'Ruang kecil, suara besar. Menyusuri tempat-tempat yang membuat sebuah kota terasa punya nadi.', image: '/editorial-portrait.jpg', platform: 'Instagram · TikTok', read: '5 min' },
  { slug: 'mereka-yang-memilih-pulang', category: 'Orang', title: 'Mereka yang memilih pulang, lalu membuat rumahnya sendiri', dek: 'Empat percakapan tentang pulang, tumbuh, dan keberanian untuk memulai lagi.', image: '/coastline.jpg', platform: 'TikTok', read: '4 min' },
  { slug: 'zine-stiker-dan-hal-kecil', category: 'Karya', title: 'Zine, stiker, dan hal-hal kecil yang menolak hilang', dek: 'Catatan dari meja kerja para pembuat gambar yang menjaga ide tetap bergerak.', image: '/studio-table.jpg', platform: 'Instagram', read: '6 min' },
];
const creators = [
  { name: 'Rara Sekar', role: 'Musisi · Yogyakarta', mark: 'RS' },
  { name: 'Jalu Kancana', role: 'Fotografer · Bandung', mark: 'JK' },
  { name: 'Nana Kautsar', role: 'Perupa · Makassar', mark: 'NK' },
];

function track(event: string, data: Record<string, string> = {}) { window.dispatchEvent(new CustomEvent('mm:analytics', { detail: { event, ...data, path: location.pathname, at: new Date().toISOString() } })); }
function Meta({ title, description }: { title: string; description: string }) { useEffect(() => { document.title = title; let m = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!m) { m = document.createElement('meta'); m.name = 'description'; document.head.appendChild(m); } m.content = description; }, [title, description]); return null; }

function Shell({ children }: { children: ReactNode }) {
  const [menu, setMenu] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const nav = [['Stories', '/stories'], ['Originals', '/originals'], ['Creators', '/creators'], ['Community', '/community']];
  return <div className="min-h-screen bg-[#f5f0e7] text-[#15120f]">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#15120f]/95 text-[#f5f0e7] backdrop-blur">
      <div className="flex h-16 items-center justify-between px-5 md:px-10">
        <Link href="/" className="flex items-center gap-3"><img src={logo} className="h-10 w-10 object-cover" alt="Majang Mejeng Media"/><span className="hidden font-mono-custom text-[9px] uppercase tracking-[.16em] text-white/55 sm:block">Majang<br/>Mejeng<br/>Media</span></Link>
        <nav className="hidden gap-7 md:flex">{nav.map(([label, href], i) => <Link key={href} href={href} className="font-mono-custom text-[10px] uppercase tracking-widest text-white/70 hover:text-[#ff5600]"><span className="mr-2 text-[#ff5600]">0{i + 1}</span>{label}</Link>)}</nav>
        <div className="flex items-center gap-4"><button onClick={() => setSearchOpen(true)} aria-label="Search"><Search size={17}/></button><Link href="/work-with-us" className="hidden rounded-full border border-[#ff5600] px-4 py-2 font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5600] sm:block">Work with us <ArrowUpRight className="inline" size={13}/></Link><button className="md:hidden" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X/> : <Menu/>}</button></div>
      </div>
      {menu && <div className="border-t border-white/10 bg-[#15120f] px-5 py-4 md:hidden">{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setMenu(false)} className="block border-b border-white/10 py-4 font-display text-2xl">{label}<ArrowUpRight className="float-right text-[#ff5600]"/></Link>)}<Link href="/work-with-us" onClick={() => setMenu(false)} className="mt-4 block bg-[#ff5600] px-4 py-3 font-mono-custom text-[10px] uppercase text-black">Mulai kolaborasi</Link></div>}
    </header>
    {children}<Footer/>{searchOpen && <SearchOverlay close={() => setSearchOpen(false)}/>}</div>;
}
function Footer() { return <footer className="bg-[#15120f] px-5 py-14 text-[#f5f0e7] md:px-10 md:py-20"><div className="mx-auto grid max-w-[1440px] gap-12 md:grid-cols-4"><div><div className="flex items-center gap-3"><img src={logo} className="h-12 w-12" alt="Majang Mejeng"/><span className="font-display text-2xl">Majang Mejeng</span></div><p className="mt-5 text-sm leading-relaxed text-white/50">Cerita, orang, tempat, budaya, dan momen yang layak dilihat lebih dekat.</p></div><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">Explore</p><div className="mt-5 grid gap-3 text-sm"><Link href="/stories">Stories</Link><Link href="/originals">Originals</Link><Link href="/creators">Creators</Link><Link href="/community">Community</Link></div></div><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">Social</p><div className="mt-5 grid gap-3 text-sm"><a href={INSTAGRAM} target="_blank" rel="noreferrer">Instagram</a><a href={TIKTOK} target="_blank" rel="noreferrer">TikTok</a><Link href="/work-with-us">Work with us</Link></div></div><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">Field note</p><p className="mt-5 text-sm text-white/50">Follow the stories. Come back for what is moving next.</p></div></div></footer>; }
function SearchOverlay({ close }: { close: () => void }) { const [q, setQ] = useState(''); const found = stories.filter(s => `${s.title} ${s.category}`.toLowerCase().includes(q.toLowerCase())); return <div className="fixed inset-0 z-[100] bg-[#15120f]/98 px-5 pt-[15vh] text-[#f5f0e7]"><div className="mx-auto max-w-4xl"><button onClick={close} className="float-right" aria-label="Close search"><X/></button><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5600]">Search / Majang Mejeng</p><div className="mt-6 flex gap-4 border-b border-white/30 pb-4"><Search className="text-[#ff5600]"/><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Cari cerita, orang, kota..." className="w-full bg-transparent font-display text-4xl outline-none md:text-6xl"/></div><div className="mt-8">{q && found.map(s => <Link key={s.slug} href={`/stories/${s.slug}`} onClick={close} className="block border-b border-white/10 py-4 text-xl">{s.title}<span className="float-right font-mono-custom text-xs text-[#ff5600]">{s.category}</span></Link>)}</div></div></div>; }
function SectionHead({ kicker, title, action, href }: { kicker: string; title: string; action?: string; href?: string }) { return <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5600]">{kicker}</p><h2 className="mt-4 max-w-4xl font-display text-5xl font-semibold leading-[.9] md:text-7xl">{title}</h2></div>{action && href && <Link href={href} className="font-mono-custom text-[9px] uppercase tracking-widest">{action} <ArrowUpRight className="inline" size={13}/></Link>}</div>; }
function StoryCard({ story }: { story: Story }) { return <Link href={`/stories/${story.slug}`} onClick={() => track('story_open', { slug: story.slug })} className="story-link group block border border-black"><div className="image-reveal relative aspect-[4/3] overflow-hidden"><img src={story.image} alt={story.title} loading="lazy" className="h-full w-full object-cover"/><span className="absolute left-3 top-3 bg-[#ff5600] px-2 py-1 font-mono-custom text-[8px] uppercase">{story.category}</span><span className="absolute bottom-3 right-3 rounded-full bg-[#f5f0e7] p-3 text-black"><ArrowUpRight size={15}/></span></div><div className="p-5"><div className="font-mono-custom text-[8px] uppercase text-black/45">{story.platform} · {story.read}</div><h3 className="mt-3 font-display text-2xl font-semibold leading-none md:text-3xl">{story.title}</h3><p className="mt-3 text-sm leading-relaxed text-black/55">{story.dek}</p><span className="mt-6 inline-block font-mono-custom text-[9px] uppercase">Buka cerita <ArrowUpRight className="inline" size={13}/></span></div></Link>; }
function Ticker() { return <div className="overflow-hidden border-b border-black py-3 font-mono-custom text-[9px] uppercase tracking-widest"><div className="marquee-track flex gap-12 whitespace-nowrap"><span>Majang Mejeng Media</span><span>Stories in motion</span><span>Indonesia</span><span>Follow the stories</span><span>Majang Mejeng Media</span><span>Stories in motion</span><span>Indonesia</span></div></div>; }
function Home() { return <Shell><Meta title="Majang Mejeng — Yang menarik, kami pajang." description="Majang Mejeng Media: cerita, orang, tempat, budaya, dan momen."/><main>
  <section className="hero-field relative overflow-hidden bg-[#090a09] px-5 pb-20 pt-20 text-[#f5f0e7] md:min-h-[820px] md:px-10 md:pt-28"><div className="hero-grid absolute inset-0 opacity-70"/><div className="hero-vignette absolute inset-0"/><div className="relative z-10 mx-auto max-w-[1440px]"><div className="mb-8 flex items-center gap-3 font-mono-custom text-[9px] uppercase tracking-widest text-white/50"><span className="h-1.5 w-1.5 rounded-full bg-[#ff5600] pulse-dot"/> Social-first media / Indonesia</div><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><h1 className="hero-title font-display text-[clamp(4rem,10vw,10rem)] font-semibold leading-[.78] tracking-[-.06em]">Yang menarik,<br/><span className="text-[#ff5600]">kami pajang.</span></h1><p className="mt-10 max-w-xl text-base leading-relaxed text-white/55 md:text-lg">Cerita, orang, budaya, dan momen yang layak dilihat dua kali. Dari social ke ruang editorial yang lebih dalam.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/stories" onClick={() => track('cta_click', { cta: 'explore' })} className="rounded-full bg-[#f5f0e7] px-5 py-3 font-mono-custom text-[10px] uppercase text-[#15120f]">Explore stories <ArrowDownRight className="inline" size={14}/></Link><Link href="/work-with-us" className="rounded-full border border-white/25 px-5 py-3 font-mono-custom text-[10px] uppercase">Work with us</Link></div></div><div className="signal-globe-wrap reveal reveal-delay-2"><SignalGlobe/></div></div></div><div className="absolute bottom-7 left-5 right-5 z-20 flex justify-between border-t border-white/15 pt-3 font-mono-custom text-[8px] uppercase tracking-widest text-white/40 md:left-10 md:right-10"><span>01 / 08 — Selamat datang di meja kami</span><span className="hidden md:inline">Scroll untuk membuka peta cerita ↓</span></div></section>
  <Ticker/>
  <section className="px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-[1440px]"><SectionHead kicker="02 / What's moving" title="Yang lagi dimajang." action="Lihat semua" href="/stories"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{stories.map(s => <StoryCard key={s.slug} story={s}/>)}</div></div></section>
  <section className="bg-[#ff5600] px-5 py-16 md:px-10 md:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono-custom text-[9px] uppercase">03 / Editorial</p><p className="mt-5 max-w-xs text-sm leading-relaxed">Di social kamu menemukan pintunya. Di sini kami membuka ruangnya lebih lebar.</p></div><Link href={`/stories/${stories[0].slug}`} className="group grid gap-6 md:grid-cols-2"><img src={stories[0].image} alt={stories[0].title} className="aspect-[4/3] w-full object-cover transition duration-700 group-hover:scale-[1.02]"/><div><p className="font-mono-custom text-[9px] uppercase">{stories[0].category} · {stories[0].read}</p><h2 className="mt-5 font-display text-4xl font-semibold leading-none md:text-6xl">{stories[0].title}</h2><p className="mt-5 text-sm">{stories[0].dek}</p><span className="mt-8 inline-block font-mono-custom text-[9px] uppercase">Baca cerita <ArrowUpRight className="inline" size={13}/></span></div></Link></div></section>
  <section className="px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-[1440px]"><SectionHead kicker="04 / Worlds" title="Kami majang banyak hal."/><div className="mt-10 grid grid-cols-2 border-t border-black md:grid-cols-3 lg:grid-cols-5">{['Stories','People','Culture','Lifestyle','Events','Food','Business','Creators','Community','Originals'].map((x,i) => <Link href="/stories" key={x} className="group border-b border-r border-black p-5 md:p-8"><span className="font-mono-custom text-[9px] text-[#ff5600]">{String(i+1).padStart(2,'0')}</span><h3 className="mt-5 font-display text-xl font-semibold">{x}</h3><ArrowUpRight className="mt-8 opacity-40" size={17}/></Link>)}</div></div></section>
  <section className="bg-[#15120f] px-5 py-16 text-[#f5f0e7] md:px-10 md:py-24"><div className="mx-auto max-w-[1440px]"><SectionHead kicker="05 / Creators" title="Kenalan dengan orangnya." action="Lihat creators" href="/creators"/><div className="mt-10 grid border-t border-white/15 md:grid-cols-3">{creators.map(c => <Link href="/creators" key={c.name} className="border-b border-white/15 p-7 md:p-10"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#ff5600] font-display text-xl text-black">{c.mark}</div><h3 className="mt-7 font-display text-3xl font-semibold">{c.name}</h3><p className="mt-2 text-sm text-white/45">{c.role}</p><ArrowUpRight className="mt-8 text-[#ff5600]"/></Link>)}</div></div></section>
  <section className="px-5 py-16 md:px-10 md:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-2"><div><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5600]">06 / Social loop</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[.88] md:text-7xl">Lihat di social.<br/>Datang lebih dalam.</h2></div><div className="grid gap-4"><Social platform="Instagram" href={INSTAGRAM} copy="Visual, reels, dan potongan cerita yang sedang bergerak."/><Social platform="TikTok" href={TIKTOK} copy="Video cepat untuk menemukan cerita berikutnya."/></div></div></section>
  <section className="bg-[#ff5600] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto flex max-w-[1440px] flex-col gap-10 md:flex-row md:items-end md:justify-between"><div><p className="font-mono-custom text-[9px] uppercase">07 / Collaboration</p><h2 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[.86] md:text-8xl">Punya sesuatu<br/>yang layak dimajang?</h2></div><Link href="/work-with-us" className="rounded-full bg-[#15120f] px-6 py-4 font-mono-custom text-[10px] uppercase text-white">Mulai ngobrol <ArrowUpRight className="inline" size={14}/></Link></div></section>
</main></Shell>; }
function SignalGlobe() { const nodes = [{x:25,y:25,label:'JKT'},{x:65,y:39,label:'BDG'},{x:39,y:62,label:'YGY'},{x:77,y:72,label:'MKS'}]; return <div className="relative mx-auto aspect-square w-full max-w-[560px]"><div className="absolute inset-[10%] rounded-full border border-white/15 bg-[radial-gradient(circle_at_35%_30%,rgba(255,122,56,.7),rgba(255,86,0,.12)_45%,transparent_70%)]"/><div className="absolute inset-[18%] rounded-full border border-dashed border-white/20"/><div className="absolute inset-[27%] rounded-full border border-white/10"/><svg className="absolute inset-[10%] h-[80%] w-[80%]" viewBox="0 0 100 100" fill="none"><path d="M5 35C28 20 39 72 55 42S79 28 96 41" stroke="#f5f0e7" strokeDasharray="2 3"/><path d="M9 75C30 61 43 25 61 50S78 79 94 65" stroke="#ff5600" strokeDasharray="2 3"/><path d="M25 25L65 39L39 62L77 72" stroke="#f5f0e7" strokeDasharray="1 3"/></svg>{nodes.map(n => <div key={n.label} className="absolute" style={{left:`${n.x}%`,top:`${n.y}%`}}><span className="block h-3 w-3 rounded-full bg-[#ff5600] shadow-[0_0_20px_#ff5600]"/><span className="ml-4 whitespace-nowrap font-mono-custom text-[9px] uppercase text-white/55">{n.label} / story</span></div>)}<div className="absolute bottom-[4%] left-[8%] right-[8%] flex justify-between font-mono-custom text-[8px] uppercase tracking-widest text-white/40"><span>Network / 04</span><span>Stories in motion</span></div></div>; }
function Social({ platform, href, copy }: { platform: string; href: string; copy: string }) { return <a href={href} target="_blank" rel="noreferrer" onClick={() => track('social_click', { platform })} className="group border border-black p-7 hover:bg-[#15120f] hover:text-white"><div className="flex justify-between"><span className="font-mono-custom text-[9px] uppercase text-[#ff5600]">{platform}</span><ArrowUpRight/></div><h3 className="mt-10 font-display text-3xl font-semibold">@majangmejeng_</h3><p className="mt-3 text-sm opacity-55">{copy}</p></a>; }

function Stories() { return <Shell><main className="px-5 py-14 md:px-10 md:py-20"><Meta title="Stories — Majang Mejeng" description="Cerita terbaru Majang Mejeng Media."/><div className="mx-auto max-w-[1440px]"><SectionHead kicker="Stories / Archive" title="Yang sedang bergerak."/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{stories.map(s => <StoryCard key={s.slug} story={s}/>)}</div></div></main></Shell>; }
function StoryPage({ slug }: { slug: string }) { const s = stories.find(x => x.slug === slug) || stories[0]; useEffect(() => track('story_view', { slug: s.slug }), [s.slug]); return <Shell><main><Meta title={`${s.title} — Majang Mejeng`} description={s.dek}/><article className="mx-auto max-w-[1440px] px-5 py-14 md:px-10 md:py-20"><Link href="/stories" className="font-mono-custom text-[9px] uppercase">← Semua stories</Link><div className="mt-12 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">{s.category} / {s.read}</p><h1 className="mt-5 font-display text-5xl font-semibold leading-[.86] md:text-8xl">{s.title}</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-black/55">{s.dek}</p></div><img src={s.image} alt={s.title} className="w-full object-cover"/></div><div className="mx-auto max-w-3xl py-20"><p className="font-display text-2xl leading-relaxed md:text-4xl">Majang Mejeng melihat cerita bukan sebagai potongan feed, tetapi sebagai pintu masuk untuk mengenal tempat, orang, dan konteks di belakangnya.</p><div className="my-12 h-px bg-black/15"/><div className="space-y-6 text-base leading-8 text-black/60"><p>Setiap cerita dimulai dari rasa ingin tahu: apa yang biasanya dilewati, siapa yang jarang didengar, dan momen apa yang layak disimpan sedikit lebih lama.</p><p>Di social, kamu menemukan pintunya. Di sini, kami membuka ruangnya lebih lebar.</p></div><Link href="/stories" className="mt-10 inline-block rounded-full bg-[#15120f] px-5 py-3 font-mono-custom text-[9px] uppercase text-white">Lanjut eksplorasi</Link></div></article></main></Shell>; }
function Originals() { return <Shell><main className="px-5 py-14 md:px-10 md:py-20"><Meta title="Originals — Majang Mejeng" description="Series editorial Majang Mejeng."/><div className="mx-auto max-w-[1440px]"><SectionHead kicker="Originals" title="Series yang kami rawat."/><div className="mt-12 grid gap-5 md:grid-cols-2">{[['Orang Lokal','Bertemu orang-orang yang membuat tempatnya punya cerita.','/editorial-portrait.jpg'],['Cerita Kota','Membaca kota lewat ruang kecil, kebiasaan, dan suara warganya.','/coastline.jpg'],['Majangin','Karya, proses, dan benda kecil yang layak mendapat ruang.','/studio-table.jpg']].map(([t,d,i]) => <div key={t} className="overflow-hidden bg-[#15120f] text-white"><img src={i} alt={t} className="aspect-video w-full object-cover"/><div className="p-7"><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">Original series</p><h2 className="mt-4 font-display text-4xl font-semibold">{t}</h2><p className="mt-3 text-sm text-white/55">{d}</p></div></div>)}</div></div></main></Shell>; }
function Creators() { return <Shell><main className="px-5 py-14 md:px-10 md:py-20"><Meta title="Creators — Majang Mejeng" description="Creator dan orang-orang di balik cerita."/><div className="mx-auto max-w-[1440px]"><SectionHead kicker="Creator directory" title="Kenalan dengan orangnya."/><div className="mt-12 grid border-t border-black md:grid-cols-3">{creators.map(c => <Link href="/work-with-us" key={c.name} className="border-b border-r border-black p-8 md:p-10"><div className="flex h-24 w-24 items-center justify-center rounded-full bg-[#ff5600] font-display text-3xl">{c.mark}</div><h2 className="mt-8 font-display text-4xl font-semibold">{c.name}</h2><p className="mt-2 text-sm text-black/50">{c.role}</p><p className="mt-8 text-sm text-black/60">Portfolio, appearances, dan kesempatan kolaborasi.</p></Link>)}</div></div></main></Shell>; }
function Community() { return <Shell><main><Meta title="Community — Majang Mejeng" description="Cerita dan inisiatif komunitas."/><section className="bg-[#15120f] px-5 py-20 text-white md:px-10 md:py-28"><div className="mx-auto max-w-[1440px]"><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">Community</p><h1 className="mt-6 max-w-5xl font-display text-6xl font-semibold leading-[.86] md:text-9xl">Yang bergerak<br/>bersama.</h1></div></section><section className="px-5 py-20 md:px-10"><div className="mx-auto max-w-3xl"><p className="font-display text-3xl leading-tight md:text-5xl">Komunitas bukan sekadar audience. Mereka adalah orang-orang yang membuat cerita terus punya tempat untuk tumbuh.</p><p className="mt-8 text-base leading-8 text-black/60">Kami membuka ruang untuk komunitas lokal, inisiatif warga, event, dan kolaborasi yang punya nilai nyata.</p></div></section></main></Shell>; }
function Work() { const [done,setDone] = useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true);track('form_submit',{form:'collaboration'});}; return <Shell><main className="px-5 py-14 md:px-10 md:py-20"><Meta title="Work With Us — Majang Mejeng" description="Campaign, content production, creator campaign, event, dan media partnership."/><div className="mx-auto max-w-[1200px]"><p className="font-mono-custom text-[9px] uppercase text-[#ff5600]">Work with us</p><h1 className="mt-6 max-w-5xl font-display text-6xl font-semibold leading-[.86] md:text-9xl">Punya sesuatu<br/>yang layak dimajang?</h1><p className="mt-8 max-w-xl text-lg text-black/55">Campaign, content production, event coverage, creator campaign, atau media partnership.</p>{done?<div className="mt-12 bg-[#ff5600] p-8"><Check/><h2 className="mt-5 font-display text-4xl font-semibold">Brief sudah masuk.</h2></div>:<form onSubmit={submit} className="mt-12 grid gap-6 border-t border-black pt-8 md:grid-cols-2"><input required className="border-b border-black bg-transparent py-3 outline-none" placeholder="Nama"/><input required type="email" className="border-b border-black bg-transparent py-3 outline-none" placeholder="Email"/><select className="border-b border-black bg-transparent py-3"><option>Brand campaign</option><option>Content production</option><option>Event coverage</option><option>Creator campaign</option><option>Media partnership</option></select><input className="border-b border-black bg-transparent py-3 outline-none" placeholder="Timeline"/><textarea required className="md:col-span-2 border border-black bg-transparent p-4 outline-none" rows={6} placeholder="Ceritakan project kamu"/><button className="w-fit rounded-full bg-[#15120f] px-6 py-4 font-mono-custom text-[10px] uppercase text-white">Kirim brief <ArrowUpRight className="inline" size={13}/></button></form>}</div></main></Shell>; }
function SocialEntry({ platform, slug }: { platform: string; slug?: string }) { const s=stories.find(x=>x.slug===slug)||stories[0]; useEffect(()=>track('social_entry',{platform,slug:s.slug}),[platform,slug,s.slug]); return <div className="min-h-screen bg-[#15120f] px-5 py-6 text-white"><Meta title={`${platform} → ${s.title}`} description={s.dek}/><div className="mx-auto max-w-md"><div className="flex items-center gap-3"><img src={logo} className="h-10 w-10" alt="Majang Mejeng"/><span className="font-mono-custom text-[9px] uppercase tracking-widest">From {platform}</span></div><img src={s.image} alt={s.title} className="mt-10 aspect-[4/5] w-full object-cover"/><p className="mt-6 font-mono-custom text-[9px] uppercase text-[#ff5600]">{s.category} · {s.read}</p><h1 className="mt-4 font-display text-4xl font-semibold leading-[.9]">{s.title}</h1><p className="mt-4 text-sm text-white/55">{s.dek}</p><Link href={`/stories/${s.slug}`} className="mt-7 block bg-[#ff5600] px-5 py-4 text-center font-mono-custom text-[10px] uppercase text-black">Lanjutkan cerita <ArrowUpRight className="inline" size={13}/></Link><div className="mt-8 grid grid-cols-2 gap-3"><a href={INSTAGRAM} target="_blank" rel="noreferrer" className="border border-white/20 p-3 text-center font-mono-custom text-[8px] uppercase">Instagram</a><a href={TIKTOK} target="_blank" rel="noreferrer" className="border border-white/20 p-3 text-center font-mono-custom text-[8px] uppercase">TikTok</a></div></div></div>; }

function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><ErrorBoundary><Switch><Route path="/" component={Home}/><Route path="/stories" component={Stories}/><Route path="/stories/:slug">{p=><StoryPage slug={p.slug}/>}</Route><Route path="/originals" component={Originals}/><Route path="/creators" component={Creators}/><Route path="/community" component={Community}/><Route path="/work-with-us" component={Work}/><Route path="/go/:platform/:slug">{p=><SocialEntry platform={p.platform} slug={p.slug}/>}</Route><Route path="/go/:platform">{p=><SocialEntry platform={p.platform}/>}</Route><Route component={NotFound}/></Switch></ErrorBoundary></WouterRouter><Toaster/></TooltipProvider></QueryClientProvider>; }
export default App;
