import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, ExternalLink, Instagram, Menu, Play, Search, Share2, Sparkles, X } from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Link, Route, Switch, useLocation, Router as WouterRouter } from 'wouter';
import logoAsset from '@assets/IMG_1920_1786731585196.png';

const queryClient = new QueryClient();
const logo = logoAsset;
const IG = 'https://www.instagram.com/majangmejeng_/';
const TT = 'https://www.tiktok.com/@majangmejeng_?lang=id-ID';
const images = ['/editorial-portrait.jpg', '/coastline.jpg', '/studio-table.jpg'];
type Story = { slug:string; category:string; title:string; dek:string; image:string; read:string; date:string; location:string; author:string };
const stories:Story[]=[
{slug:'pasar-santa-dan-kota-yang-mendengar',category:'Places',title:'Di balik riuhnya pasar, ada kota yang sedang belajar mendengar',dek:'Ruang kecil, suara besar. Menyusuri tempat-tempat yang membuat sebuah kota terasa punya nadi.',image:images[0],read:'05 min',date:'12 Aug 2026',location:'Indonesia',author:'Majang Mejeng Editorial'},
{slug:'mereka-yang-memilih-pulang',category:'People',title:'Mereka yang memilih pulang, lalu membuat rumahnya sendiri',dek:'Empat percakapan tentang pulang, tumbuh, dan keberanian untuk memulai lagi.',image:images[1],read:'04 min',date:'08 Aug 2026',location:'Jawa Timur',author:'Majang Mejeng Editorial'},
{slug:'zine-stiker-dan-hal-kecil',category:'Creators',title:'Zine, stiker, dan hal-hal kecil yang menolak hilang',dek:'Catatan dari meja kerja para pembuat gambar yang menjaga ide tetap bergerak.',image:images[2],read:'06 min',date:'02 Aug 2026',location:'Indonesia',author:'Majang Mejeng Editorial'},
{slug:'warung-kecil-cerita-besar',category:'Food',title:'Warung kecil, cerita besar, dan resep yang berpindah tangan',dek:'Tentang rasa yang bertahan karena orang-orang memilih untuk terus membuatnya.',image:images[1],read:'03 min',date:'29 Jul 2026',location:'Jawa Timur',author:'Majang Mejeng Editorial'},
{slug:'malam-yang-mengumpulkan-orang',category:'Culture',title:'Malam yang mengumpulkan orang-orang yang biasanya berjalan sendiri',dek:'Ketika musik, ruang publik, dan percakapan menjadi alasan untuk bertemu.',image:images[0],read:'05 min',date:'22 Jul 2026',location:'Indonesia',author:'Majang Mejeng Editorial'},
{slug:'kota-dari-meja-kerja',category:'Ideas',title:'Kota dari meja kerja: bagaimana ide kecil menemukan jalannya',dek:'Sebuah catatan visual tentang proses, kegagalan, dan keberanian mengulang.',image:images[2],read:'07 min',date:'16 Jul 2026',location:'Indonesia',author:'Majang Mejeng Editorial'}];
const categories=['All','People','Places','Culture','Food','Ideas','Creators'];
const worlds=['People','Places','Culture','Food','Ideas','Creators'];
const creators=[{name:'Rara Sekar',role:'Musisi',city:'Yogyakarta',image:images[0]},{name:'Jalu Kancana',role:'Fotografer',city:'Bandung',image:images[1]},{name:'Nana Kautsar',role:'Perupa',city:'Makassar',image:images[2]},{name:'Aksa Putra',role:'Pembuat film',city:'Surabaya',image:images[0]}];
const faqs=[['Apa itu Majang Mejeng?','Majang Mejeng adalah media social-first yang membawa sinyal dari Instagram dan TikTok ke cerita yang lebih dalam tentang orang, tempat, karya, dan culture.'],['Apa saja yang kalian liput?','People, Places, Culture, Food, Ideas, dan Creators. Taxonomy ini dapat berkembang mengikuti karakter komunitas dan editorial.'],['Bagaimana cara mengirim cerita?','Gunakan halaman Submit Story atau kirim brief. Kami akan menilai konteks, kualitas cerita, dan kecocokannya dengan editorial.'],['Apakah menerima creator baru?','Ya. Creator dapat masuk melalui open call, editorial discovery, atau collaboration.'],['Bagaimana brand bisa bekerja sama?','Kami membuka campaign, event coverage, editorial partnership, creator partnership, dan media placement.'],['Apakah konten social otomatis dipindahkan ke website?','Tidak. Social menjadi signal dan pintu masuk. Website memberi konteks, arsip, dan pengalaman editorial yang lebih dalam.']];
function track(event:string,data:Record<string,unknown>={}){window.dispatchEvent(new CustomEvent('mm:analytics',{detail:{event,data,path:window.location.pathname,at:new Date().toISOString()}}))}
function useReveal(){useEffect(()=>{const nodes=[...document.querySelectorAll<HTMLElement>('[data-reveal]')];if(!('IntersectionObserver'in window)){nodes.forEach(n=>n.classList.add('is-visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});nodes.forEach(n=>io.observe(n));return()=>io.disconnect()},[])}
function Meta({title,description}:{title:string;description:string}){useEffect(()=>{document.title=title;let m=document.querySelector('meta[name="description"]') as HTMLMetaElement|null;if(!m){m=document.createElement('meta');m.name='description';document.head.appendChild(m)}m.content=description},[title,description]);return null}
function Progress(){const[p,setP]=useState(0);useEffect(()=>{const on=()=>{const h=document.documentElement.scrollHeight-innerHeight;setP(h>0?scrollY/h:0)};on();addEventListener('scroll',on,{passive:true});return()=>removeEventListener('scroll',on)},[]);return <div className="scroll-progress"><span style={{transform:`scaleY(${p})`}}/></div>}
function Cursor(){const[enabled,setEnabled]=useState(false);const[x,setX]=useState(-100);const[y,setY]=useState(-100);const[label,setLabel]=useState('');useEffect(()=>{const mq=matchMedia('(pointer:fine)');setEnabled(mq.matches);if(!mq.matches)return;const move=(e:MouseEvent)=>{setX(e.clientX);setY(e.clientY)};const over=(e:MouseEvent)=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-cursor]');setLabel(el?.dataset.cursor||'')};addEventListener('mousemove',move);document.addEventListener('mouseover',over);return()=>{removeEventListener('mousemove',move);document.removeEventListener('mouseover',over)}},[]);return enabled?<div className={`cursor ${label?'cursor-active':''}`} style={{left:x,top:y}}>{label}</div>:null}
function Shell({children}:{children:ReactNode}){const[menu,setMenu]=useState(false);const[search,setSearch]=useState(false);const[location]=useLocation();const nav=[['Stories','/stories'],['Originals','/originals'],['People','/people'],['Culture','/culture']];useEffect(()=>setMenu(false),[location]);return <div className="mm-shell"><Progress/><Cursor/><header className="mm-header"><Link href="/" className="brand" aria-label="Majang Mejeng home"><img src={logo} alt="Majang Mejeng Media"/><span>MAJANG<br/>MEJENG<br/>MEDIA</span></Link><nav className="desktop-nav">{nav.map(([l,h],i)=><Link key={h} href={h} className={location===h?'active':''}><b>0{i+1}</b>{l}</Link>)}</nav><div className="header-actions"><button aria-label="Search" onClick={()=>setSearch(true)}><Search size={17}/></button><Link className="header-cta" href="/collaborate">Collaborate <ArrowUpRight size={12}/></Link><button aria-label="Menu" className="menu-button" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<MobileMenu close={()=>setMenu(false)}/>} {children}<Footer/>{search&&<SearchOverlay close={()=>setSearch(false)}/>}</div>}
function MobileMenu({close}:{close:()=>void}){return <div className="mobile-menu"><div className="mobile-menu-head"><span className="eyebrow">NAVIGATION / 2026</span><button onClick={close} aria-label="Close menu"><X/></button></div>{[['Stories','/stories'],['Originals','/originals'],['People','/people'],['Places','/places'],['Culture','/culture'],['Creators','/creators'],['Community','/community'],['About','/about']].map(([l,h],i)=><Link key={h} href={h} onClick={close}><span>{String(i+1).padStart(2,'0')}</span><strong>{l}</strong><ArrowUpRight/></Link>)}<Link href="/collaborate" className="mobile-menu-cta" onClick={close}>Start a collaboration <ArrowUpRight/></Link></div>}
function SearchOverlay({close}:{close:()=>void}){const[q,setQ]=useState('');const[cat,setCat]=useState('All');const found=useMemo(()=>stories.filter(s=>(cat==='All'||s.category===cat)&&`${s.title} ${s.category} ${s.dek}`.toLowerCase().includes(q.toLowerCase())),[q,cat]);return <div className="search-overlay" role="dialog" aria-modal="true"><div className="search-inner"><button aria-label="Close search" className="close-search" onClick={close}><X/></button><span className="eyebrow orange">SEARCH / MAJANG MEJENG</span><div className="search-field"><Search/><input autoFocus placeholder="Cari cerita, orang, tempat, ide..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="filter-row">{categories.map(c=><button key={c} className={cat===c?'selected':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="search-results">{found.length?found.map(s=><Link key={s.slug} href={`/stories/${s.slug}`} onClick={close}><span>{s.category} · {s.read}</span><strong>{s.title}</strong><ArrowUpRight/></Link>):<p className="empty-state">Tidak ada cerita yang cocok. Coba kata kunci lain.</p>}</div></div></div>}
function Footer(){return <footer className="mm-footer"><div className="footer-grid"><div className="footer-intro"><div className="footer-brand"><img src={logo} alt="Majang Mejeng"/><strong>Majang Mejeng</strong></div><p>Media lokal yang memperpanjang cerita dari social menjadi pengalaman yang bisa dijelajahi, diingat, dan dibagikan.</p><div className="footer-social"><a href={IG} target="_blank" rel="noreferrer">Instagram <ExternalLink size={12}/></a><a href={TT} target="_blank" rel="noreferrer">TikTok <ExternalLink size={12}/></a></div></div><div><span className="eyebrow">EXPLORE</span><Link href="/stories">Stories</Link><Link href="/originals">Originals</Link><Link href="/people">People</Link><Link href="/places">Places</Link><Link href="/culture">Culture</Link></div><div><span className="eyebrow">DISCOVER</span><Link href="/creators">Creators</Link><Link href="/community">Community</Link><Link href="/about">About</Link><Link href="/submit-story">Submit story</Link></div><div><span className="eyebrow">COLLABORATE</span><p>Campaign, event, editorial, creator partnership.</p><Link href="/collaborate">Kirim brief <ArrowUpRight size={12}/></Link></div></div><div className="footer-bottom"><span>MAJANG MEJENG MEDIA / INDONESIA</span><span>FOLLOW WHAT IS MOVING.</span><span><Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link></span></div></footer>}
function Home(){useReveal();return <><Meta title="Majang Mejeng — Follow what is moving" description="Majang Mejeng Media — cerita, orang, tempat, karya, dan culture dari social ke pengalaman editorial."/><main><Hero/><Signal/><Journey/><Moving/><Worlds/><PeopleBand/><SocialCurrent/><Testimonials/><FAQ/><FinalCTA/></main></>}
function Hero(){return <section className="hero"><div className="hero-grid"/><div className="hero-glow"/><div className="hero-meta"><span><i/> SOCIAL-FIRST MEDIA / INDONESIA</span><span>01 — 10</span></div><div className="hero-center"><div className="hero-copy" data-reveal><span className="eyebrow orange">01 / THE STORY STARTS HERE</span><h1>Yang menarik,<br/><em>kami pajang.</em></h1><p>Dari satu post, satu tempat, satu orang — kami mengikuti ceritanya sampai kamu ingin melihat lebih dekat.</p><div className="hero-actions"><Link href="/stories" data-cursor="EXPLORE">Explore stories <ArrowDownRight size={14}/></Link><a href={IG} target="_blank" rel="noreferrer">Instagram <Instagram size={13}/></a></div></div><div className="signal-orb" data-cursor="DRAG"><span className="orb-core"/><i/><i/><i/><b>SOCIAL</b><b>STORY</b></div></div><button className="scroll-hint" onClick={()=>document.querySelector('#signal')?.scrollIntoView({behavior:'smooth'})}>SCROLL TO CONTINUE <ArrowDown size={13}/></button></section>}
function Signal(){return <section className="signal section-light" id="signal"><div className="chapter"><span className="eyebrow">02 / THE SIGNAL</span><span>WE NOTICE WHAT MOVES.</span></div><div data-reveal><p className="giant">Social menangkap <em>momen.</em><br/>Kami mencari <em>ceritanya.</em></p><div className="split"><p>Majang Mejeng berada di antara scroll cepat dan rasa ingin tahu yang lebih dalam. Kami mengambil sinyal dari Instagram dan TikTok, lalu memberi konteks, wajah, tempat, dan waktu.</p><p className="mono orange">ONE POST → ONE QUESTION → ONE STORY</p></div></div></section>}
function Journey(){const chapters=[['03.1','Mulai dari yang bergerak.','Social media menangkap momen ketika ia sedang terjadi. Kami tidak ingin berhenti di sana.',images[0]],['03.2','Lalu kami mendekat.','Orang, tempat, karya, dan kebiasaan mendapat ruang untuk bernapas — bukan sekadar thumbnail.',images[1]],['03.3','Sampai ceritanya punya tempat tinggal.','Website menjadi arsip yang hidup: perjalanan dari scroll cepat menuju rasa ingin tahu yang lebih dalam.',images[2]]];return <section className="journey section-dark"><div className="journey-rail"><span className="eyebrow">03 / THE JOURNEY</span><div className="rail"><i/></div><span className="mono">EVERY SCROLL REVEALS ANOTHER LAYER.</span></div><div>{chapters.map(([n,t,c,img],i)=><article className="journey-scene" key={n} data-reveal><div className="scene-image" data-cursor="VIEW"><span>{n}</span><img src={img} alt="" loading="lazy"/></div><div className="scene-copy"><span className="eyebrow orange">FIELD NOTE / {n}</span><h2>{t}</h2><p>{c}</p><span className="mono faded">0{i+1} / 03</span></div></article>)}</div></section>}
function Moving(){return <section className="moving section-light"><div className="section-head"><span className="eyebrow">04 / WHAT'S MOVING</span><Link href="/stories">View all stories <ArrowUpRight size={13}/></Link></div><Link href={`/stories/${stories[0].slug}`} className="feature" data-cursor="READ"><div className="feature-image"><img src={stories[0].image} alt=""/><span>{stories[0].category}</span></div><div className="feature-copy"><span className="mono orange">FEATURED STORY / {stories[0].read}</span><h2>{stories[0].title}</h2><p>{stories[0].dek}</p><span className="read-link">Read story <ArrowUpRight size={16}/></span></div></Link><div className="story-strip">{stories.slice(1,4).map(s=><Link key={s.slug} href={`/stories/${s.slug}`}><span>{s.category}</span><strong>{s.title}</strong><small>{s.read}</small><ArrowRight size={15}/></Link>)}</div></section>}
function Worlds(){return <section className="worlds section-tan"><div className="world-intro" data-reveal><span className="eyebrow">05 / THE WORLDS</span><h2>Different worlds.<br/><em>One current.</em></h2><p>Masuk dari topik mana pun. Ikuti cerita ke mana pun ia bergerak.</p></div><div className="world-list">{worlds.map((w,i)=><Link href={`/stories?category=${w}`} key={w} onClick={()=>track('world_open',{world:w})}><span>0{i+1}</span><strong>{w}</strong><ArrowUpRight/></Link>)}</div></section>}
function PeopleBand(){const[active,setActive]=useState(0);const next=()=>setActive(v=>(v+1)%creators.length);const prev=()=>setActive(v=>(v-1+creators.length)%creators.length);const c=creators[active];return <section className="people section-dark"><div className="section-head"><span className="eyebrow">06 / THE PEOPLE</span><Link href="/creators">Explore creators <ArrowUpRight size={13}/></Link></div><div className="people-title"><h2>Behind every story,<br/><em>there is a person.</em></h2><p>Musisi, fotografer, perupa, pemilik tempat, penggerak komunitas, dan orang-orang yang membuat sebuah kota terasa hidup.</p></div><div className="people-carousel"><div className="people-image" data-cursor="MEET"><img key={c.name} src={c.image} alt={c.name}/><span>0{active+1} / 0{creators.length}</span></div><div className="people-copy"><span className="eyebrow orange">CREATOR PROFILE</span><h3>{c.name}</h3><p>{c.role} · {c.city}</p><Link href="/creators">Open profile <ArrowUpRight size={14}/></Link><div className="carousel-controls"><button onClick={prev} aria-label="Previous creator"><ArrowLeft/></button><button onClick={next} aria-label="Next creator"><ArrowRight/></button></div></div></div></section>}
function SocialCurrent(){return <section className="social-current section-orange"><div data-reveal><span className="eyebrow">07 / THE SOCIAL CURRENT</span><h2>From social<br/><em>to story.</em></h2></div><div className="social-panels"><a href={IG} target="_blank" rel="noreferrer" data-cursor="OPEN"><span>INSTAGRAM</span><strong>@majangmejeng_</strong><ArrowUpRight/></a><a href={TT} target="_blank" rel="noreferrer" data-cursor="OPEN"><span>TIKTOK</span><strong>@majangmejeng_</strong><ArrowUpRight/></a></div><p className="social-note">Lihat di social. Lalu kembali ke sini saat kamu ingin tahu lebih banyak.</p></section>}
function Testimonials(){const items=['“Majang Mejeng membuat campaign kami terasa seperti cerita, bukan iklan.”','“Yang paling kuat adalah cara mereka menemukan konteks di balik sebuah momen.”','“Kami datang untuk coverage, pulang dengan cerita yang punya umur lebih panjang.”'];const[i,setI]=useState(0);return <section className="testimonials section-light"><div className="section-head"><span className="eyebrow">08 / WHAT PEOPLE SAY</span><span className="mono">0{i+1} / 03</span></div><blockquote>{items[i]}</blockquote><div className="quote-controls"><button onClick={()=>setI((i+2)%3)} aria-label="Previous testimonial"><ArrowLeft/></button><button onClick={()=>setI((i+1)%3)} aria-label="Next testimonial"><ArrowRight/></button></div></section>}
function FAQ(){const[open,setOpen]=useState<number|null>(null);return <section className="faq section-tan"><div className="faq-intro"><span className="eyebrow">09 / FAQ</span><h2>Questions,<br/><em>answered.</em></h2><p>Beberapa hal yang paling sering ingin diketahui sebelum cerita dimulai.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-item ${open===i?'open':''}`} key={q}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown/></button><div className="faq-answer"><p>{a}</p></div></div>)}</div></section>}
function FinalCTA(){return <section className="final-cta section-light"><span className="eyebrow">10 / COLLABORATION / OPEN</span><h2>Punya sesuatu<br/><em>untuk dipajang?</em></h2><p>Ceritakan campaign, event, brand, komunitas, atau ide yang sedang bergerak.</p><div className="cta-row"><Link href="/collaborate">Kirim brief <ArrowUpRight/></Link><Link href="/submit-story" className="secondary">Submit story <ArrowUpRight/></Link></div></section>}
function Archive({category='All'}:{category?:string}){const[active,setActive]=useState(category==='All'?'All':category);const filtered=active==='All'?stories:stories.filter(s=>s.category.toLowerCase()===active.toLowerCase());useReveal();return <Page title="Stories" kicker="Stories / The living archive"><div className="archive-toolbar"><div className="filter-row">{categories.map(c=><button key={c} className={active===c?'selected':''} onClick={()=>setActive(c)}>{c}</button>)}</div><span className="mono">{filtered.length} STORIES</span></div><div className="archive-grid">{filtered.map((s,i)=><Link className="archive-card" href={`/stories/${s.slug}`} key={s.slug} data-reveal data-cursor="READ"><div className="archive-image"><img src={s.image} alt=""/><span>{String(i+1).padStart(2,'0')}</span></div><span className="eyebrow orange">{s.category} · {s.read}</span><h2>{s.title}</h2><p>{s.dek}</p><small>{s.date} · {s.location}</small></Link>)}</div></Page>}
function StoryDetail({slug}:{slug:string}){const s=stories.find(x=>x.slug===slug);if(!s)return <NotFound/>;const idx=stories.findIndex(x=>x.slug===slug),next=stories[(idx+1)%stories.length],prev=stories[(idx-1+stories.length)%stories.length];return <Page title={s.title} kicker={`${s.category} / ${s.read}`}><article className="story-detail"><div className="story-meta"><span>{s.date}</span><span>{s.location}</span><span>{s.author}</span></div><img className="story-hero-image" src={s.image} alt=""/><div className="story-layout"><aside><span className="eyebrow">READING</span><strong>{s.read}</strong><button onClick={()=>navigator.clipboard?.writeText(window.location.href)}><Share2 size={14}/> Share</button></aside><div className="story-body"><p className="lead">{s.dek}</p><p>Setiap tempat menyimpan ritme yang tidak selalu terlihat dari satu layar. Majang Mejeng datang untuk mendekat: mendengar, mengamati, dan menyusun kembali potongan-potongan kecil menjadi cerita yang bisa tinggal lebih lama.</p><div className="pullquote">“Bukan sekadar thumbnail. Ada manusia, tempat, dan waktu di belakang setiap sinyal.”</div><img src={images[(idx+1)%images.length]} alt="Editorial detail"/><p>Ini adalah ruang editorial untuk orang, tempat, karya, dan kebiasaan yang sedang bergerak. Bukan jawaban terakhir — hanya undangan untuk melihat sekali lagi.</p></div></div><div className="story-nextprev"><Link href={`/stories/${prev.slug}`}><ArrowLeft/><span>Previous<br/><strong>{prev.title}</strong></span></Link><Link href={`/stories/${next.slug}`}><span>Next<br/><strong>{next.title}</strong></span><ArrowRight/></Link></div></article></Page>}
function CreatorIndex(){return <Page title="Creators" kicker="People / The people behind the stories"><div className="creator-grid">{creators.map((c,i)=><Link href="/creators" key={c.name} className="creator-card"><div><img src={c.image} alt={c.name}/><span>0{i+1}</span></div><span className="eyebrow orange">{c.role}</span><h2>{c.name}</h2><p>{c.city}</p></Link>)}</div></Page>}
function Originals(){return <Page title="Originals" kicker="Originals / Film · video · special projects"><div className="original-hero"><div><span className="eyebrow orange">WATCH / ORIGINALS</span><h2>Stories built<br/><em>for the screen.</em></h2><p>Film pendek, mini series, photo essay, dan special projects yang memberi cerita bentuk lain.</p></div><div className="video-poster" data-cursor="PLAY"><img src={images[1]} alt="Original project"/><span><Play fill="currentColor"/> PLAY REEL</span></div></div><div className="original-list">{stories.slice(0,4).map((s,i)=><Link href={`/stories/${s.slug}`} key={s.slug}><span>0{i+1}</span><strong>{s.title}</strong><small>{s.category} · {s.read}</small><ArrowUpRight/></Link>)}</div></Page>}
function GenericHub({title,kicker,items}:{title:string;kicker:string;items:string[]}){return <Page title={title} kicker={kicker}><div className="hub-list">{items.map((x,i)=><Link href="/stories" key={x}><span>0{i+1}</span><strong>{x}</strong><ArrowUpRight/></Link>)}</div><div className="hub-note"><Sparkles size={18}/><p>Masuk dari sini, lalu ikuti ceritanya lebih jauh melalui Stories dan related content.</p></div></Page>}
function About(){return <Page title="About" kicker="About / Who we are"><div className="about-lead"><p>Majang Mejeng adalah media social-first yang memperlambat apa yang biasanya berlalu terlalu cepat.</p><span className="mono">NOTICE → CONTEXT → STORY → COMMUNITY</span></div><div className="about-grid"><div><span className="eyebrow">EDITORIAL PHILOSOPHY</span><h2>Kami tidak mengejar semua yang ramai. Kami mencari apa yang punya alasan untuk tinggal.</h2></div><div><p>Social adalah tempat kita menemukan sinyal. Website adalah tempat kita memberi sinyal itu konteks dan umur yang lebih panjang.</p><p>Kami percaya orang, tempat, karya, dan culture lokal tidak kekurangan cerita. Yang kurang adalah ruang untuk melihatnya dengan lebih dekat.</p></div></div><FAQ/></Page>}
function WorkForm({story=false}:{story?:boolean}){const[done,setDone]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(e.currentTarget.checkValidity()){setDone(true);track(story?'story_submitted':'brief_submitted')}};if(done)return <div className="success-card"><span className="eyebrow orange">RECEIVED</span><h2>Terima kasih. Ceritanya sudah masuk.</h2><p>Form UI sudah siap. Untuk production, endpoint dapat dihubungkan ke email, CRM, atau Supabase.</p></div>;return <form className="brief-form" onSubmit={submit}><label>Nama<input required name="name" placeholder="Nama lengkap"/></label><label>Email<input required type="email" name="email" placeholder="email@contoh.com"/></label>{story?<label>Judul cerita<input required name="title" placeholder="Judul cerita"/></label>:<label>Jenis kolaborasi<select name="type" defaultValue="campaign"><option value="campaign">Brand campaign</option><option value="event">Event / coverage</option><option value="creator">Creator partnership</option><option value="editorial">Editorial partnership</option></select></label>}<label>{story?'Ceritakan ide':'Ceritakan project'}<textarea required name="message" rows={7} placeholder="Tulis konteks, tujuan, dan hal penting lainnya..."/></label><button type="submit">{story?'Submit story':'Kirim brief'} <ArrowUpRight size={15}/></button></form>}
function Work({story=false}:{story?:boolean}){return <Page title={story?'Submit story':'Collaborate with us'} kicker={story?'Community / Open call':'Collaboration / Open'}><div className="work-grid"><div className="work-copy"><p className="lead">{story?'Punya cerita yang layak dilihat lebih dekat? Kirimkan sinyal awalnya.':'Campaign, event, editorial, creator partnership — ceritakan apa yang sedang kamu gerakkan.'}</p><p>{story?'Kami akan menilai konteks, kualitas cerita, dan kecocokannya dengan editorial.':'Kami membuka ruang untuk kolaborasi yang punya cerita, bukan hanya placement.'}</p><div className="work-facts"><span>EDITORIAL</span><span>CREATOR</span><span>CAMPAIGN</span><span>COMMUNITY</span></div></div><WorkForm story={story}/></div></Page>}
function Legal({type}:{type:'Privacy'|'Terms'}){return <Page title={type} kicker={`System / ${type}`}><div className="legal"><p className="lead">Dokumen ini menjadi placeholder kebijakan publik untuk tahap website. Sebelum production launch, isi dengan kebijakan final yang sesuai dengan data collection, analytics, cookies, dan kebutuhan hukum bisnis.</p><h2>{type==='Privacy'?'Privacy principles':'Terms of use'}</h2><p>Majang Mejeng menghargai konteks, atribusi, hak cipta, dan privasi. Informasi yang dikirim melalui form hanya digunakan untuk menindaklanjuti permintaan dan kebutuhan operasional yang dijelaskan pada kebijakan final.</p><h2>Contact</h2><p>Untuk pertanyaan mengenai dokumen ini, gunakan halaman Collaborate atau kanal social resmi Majang Mejeng.</p></div></Page>}
function Page({title,kicker,children}:{title:string;kicker:string;children:ReactNode}){useReveal();return <><Meta title={`${title} — Majang Mejeng`} description={kicker}/><main className="inner-page"><div className="inner-hero"><span className="eyebrow orange">{kicker}</span><h1 data-reveal>{title}</h1></div>{children}</main></>}
function Routes(){return <Switch><Route path="/" component={Home}/><Route path="/stories/:slug">{p=><StoryDetail slug={p.slug}/>}</Route><Route path="/stories">{()=>{const p=new URLSearchParams(window.location.search);return <Archive category={p.get('category')||'All'}/>}}</Route><Route path="/originals" component={Originals}/><Route path="/creators" component={CreatorIndex}/><Route path="/people">{()=> <GenericHub title="People" kicker="People / Stories about people" items={['Creators','Entrepreneurs','Artists','Community leaders','People to watch']}/>}</Route><Route path="/places">{()=> <GenericHub title="Places" kicker="Places / Local guides and hidden corners" items={['Cities','Hidden places','Food spots','Local guides','Places to return to']}/>}</Route><Route path="/culture">{()=> <GenericHub title="Culture" kicker="Culture / Events · traditions · trends" items={['Local culture','Events','Youth culture','Traditions','What is changing']}/>}</Route><Route path="/community">{()=> <GenericHub title="Community" kicker="Community / People who make things happen" items={['Open call','Submit story','Events','Community projects','Meetups']}/>}</Route><Route path="/about" component={About}/><Route path="/collaborate">{()=> <Work/>}</Route><Route path="/work-with-us">{()=> <Work/>}</Route><Route path="/submit-story">{()=> <Work story/>}</Route><Route path="/privacy">{()=> <Legal type="Privacy"/>}</Route><Route path="/terms">{()=> <Legal type="Terms"/>}</Route><Route><NotFound/></Route></Switch>}
export default function App(){return <ErrorBoundary><QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base="/MAJANGMEJENG"><Shell><Routes/></Shell></WouterRouter><Toaster/></TooltipProvider></QueryClientProvider></ErrorBoundary>}
