import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, Instagram, Menu, Search, X } from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Link, Route, Switch, Router as WouterRouter } from 'wouter';
import logoAsset from '@assets/IMG_1920_1786731585196.png';

const queryClient = new QueryClient();
const logo = logoAsset;
const INSTAGRAM = 'https://www.instagram.com/majangmejeng_/';
const TIKTOK = 'https://www.tiktok.com/@majangmejeng_?lang=id-ID';
const stories = [
  { slug: 'pasar-santa-dan-kota-yang-mendengar', category: 'Kota', title: 'Di balik riuhnya pasar, ada kota yang sedang belajar mendengar', dek: 'Ruang kecil, suara besar. Menyusuri tempat-tempat yang membuat sebuah kota terasa punya nadi.', image: '/editorial-portrait.jpg', platform: 'Instagram · TikTok', read: '05 min' },
  { slug: 'mereka-yang-memilih-pulang', category: 'Orang', title: 'Mereka yang memilih pulang, lalu membuat rumahnya sendiri', dek: 'Empat percakapan tentang pulang, tumbuh, dan keberanian untuk memulai lagi.', image: '/coastline.jpg', platform: 'TikTok', read: '04 min' },
  { slug: 'zine-stiker-dan-hal-kecil', category: 'Karya', title: 'Zine, stiker, dan hal-hal kecil yang menolak hilang', dek: 'Catatan dari meja kerja para pembuat gambar yang menjaga ide tetap bergerak.', image: '/studio-table.jpg', platform: 'Instagram', read: '06 min' },
];
const creators = [
  { name: 'Rara Sekar', role: 'Musisi · Yogyakarta', mark: 'RS' },
  { name: 'Jalu Kancana', role: 'Fotografer · Bandung', mark: 'JK' },
  { name: 'Nana Kautsar', role: 'Perupa · Makassar', mark: 'NK' },
];
const worlds = ['People', 'Places', 'Culture', 'Food', 'Ideas', 'Creators'];

function track(event: string, data: Record<string, string> = {}) { window.dispatchEvent(new CustomEvent('mm:analytics', { detail: { event, ...data, path: location.pathname, at: new Date().toISOString() } })); }
function Meta({ title, description }: { title: string; description: string }) { useEffect(() => { document.title = title; let m = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!m) { m = document.createElement('meta'); m.name = 'description'; document.head.appendChild(m); } m.content = description; }, [title, description]); return null; }

function Shell({ children }: { children: ReactNode }) {
  const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false);
  const nav = [['Stories','/stories'],['Originals','/originals'],['Creators','/creators'],['Community','/community']];
  return <div className="page-shell min-h-screen bg-[#f2eee5] text-[#11110f]">
    <header className="fixed inset-x-0 top-0 z-[80] border-b border-white/10 bg-[#11110f]/90 text-[#f2eee5] backdrop-blur-md">
      <div className="mx-auto flex h-[72px] max-w-[1600px] items-center justify-between px-5 md:px-10">
        <Link href="/" className="flex items-center gap-3" aria-label="Majang Mejeng home"><img src={logo} className="h-9 w-9 object-cover" alt="Majang Mejeng Media"/><span className="hidden font-mono-custom text-[9px] uppercase leading-[1.15] tracking-[.15em] text-white/55 sm:block">Majang<br/>Mejeng<br/>Media</span></Link>
        <nav className="hidden items-center gap-7 md:flex">{nav.map(([label,href],i)=><Link key={href} href={href} className="font-mono-custom text-[9px] uppercase tracking-[.15em] text-white/65 transition hover:text-[#ff5a00]"><span className="mr-2 text-[#ff5a00]">0{i+1}</span>{label}</Link>)}</nav>
        <div className="flex items-center gap-3"><button aria-label="Search" onClick={()=>setSearch(true)} className="rounded-full p-2 hover:bg-white/10"><Search size={17}/></button><Link href="/work-with-us" className="hidden border border-[#ff5a00] px-4 py-2 font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5a00] transition hover:bg-[#ff5a00] hover:text-black sm:block">Work with us <ArrowUpRight className="ml-1 inline" size={12}/></Link><button aria-label="Menu" className="rounded-full p-2 md:hidden" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div>
      </div>
      {menu&&<div className="border-t border-white/10 bg-[#11110f] px-5 py-4 md:hidden">{nav.map(([label,href],i)=><Link key={href} href={href} onClick={()=>setMenu(false)} className="flex items-center justify-between border-b border-white/10 py-4 font-display text-3xl">{label}<span className="font-mono-custom text-xs text-[#ff5a00]">0{i+1}</span></Link>)}<Link href="/work-with-us" onClick={()=>setMenu(false)} className="mt-4 block bg-[#ff5a00] px-4 py-4 font-mono-custom text-[9px] uppercase text-black">Start a collaboration <ArrowUpRight className="inline" size={13}/></Link></div>}
    </header>
    {children}<Footer/>{search&&<SearchOverlay close={()=>setSearch(false)}/>}</div>;
}
function Footer(){return <footer className="bg-[#11110f] px-5 py-16 text-[#f2eee5] md:px-10 md:py-24"><div className="mx-auto max-w-[1600px]"><div className="grid gap-12 border-b border-white/15 pb-16 md:grid-cols-[1.5fr_.7fr_.7fr_.7fr]"><div><div className="flex items-center gap-3"><img src={logo} className="h-11 w-11" alt="Majang Mejeng"/><span className="font-display text-2xl">Majang Mejeng</span></div><p className="mt-6 max-w-md text-sm leading-relaxed text-white/45">Media lokal yang memperpanjang cerita dari social menjadi pengalaman yang bisa dijelajahi, diingat, dan dibagikan.</p></div><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">Explore</p><div className="mt-5 grid gap-3 text-sm text-white/70"><Link href="/stories">Stories</Link><Link href="/originals">Originals</Link><Link href="/creators">Creators</Link><Link href="/community">Community</Link></div></div><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">Social</p><div className="mt-5 grid gap-3 text-sm text-white/70"><a href={INSTAGRAM} target="_blank" rel="noreferrer">Instagram</a><a href={TIKTOK} target="_blank" rel="noreferrer">TikTok</a><Link href="/work-with-us">Work with us</Link></div></div><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">Contact</p><p className="mt-5 text-sm text-white/50">Untuk cerita, campaign, event, dan kolaborasi.</p><Link href="/work-with-us" className="mt-4 inline-block font-mono-custom text-[9px] uppercase text-white">Kirim brief <ArrowUpRight className="inline" size={12}/></Link></div></div><div className="flex flex-col justify-between gap-3 pt-5 font-mono-custom text-[8px] uppercase tracking-widest text-white/35 md:flex-row"><span>Majang Mejeng Media / Indonesia</span><span>Follow what is moving.</span></div></div></footer>}
function SearchOverlay({close}:{close:()=>void}){const[q,setQ]=useState('');const found=stories.filter(s=>`${s.title} ${s.category}`.toLowerCase().includes(q.toLowerCase()));return <div className="fixed inset-0 z-[100] overflow-y-auto bg-[#11110f]/[.98] px-5 pt-[15vh] text-[#f2eee5]"><div className="mx-auto max-w-5xl"><button onClick={close} aria-label="Close search" className="float-right rounded-full border border-white/20 p-2"><X/></button><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5a00]">Search / Majang Mejeng</p><div className="mt-8 flex gap-4 border-b border-white/30 pb-5"><Search className="mt-2 text-[#ff5a00]"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari cerita, orang, tempat..." className="w-full bg-transparent font-display text-4xl outline-none md:text-7xl"/></div><div className="mt-8">{q&&found.map(s=><Link key={s.slug} href={`/stories/${s.slug}`} onClick={close} className="block border-b border-white/10 py-5 font-display text-2xl hover:text-[#ff5a00]">{s.title}<span className="float-right mt-2 font-mono-custom text-[9px] uppercase text-white/40">{s.category}</span></Link>)}</div></div></div>}
function Signal(){return <div className="relative mx-auto aspect-square w-[min(72vw,580px)] rounded-full border border-white/10"><div className="absolute inset-[8%] rounded-full border border-[#ff5a00]/35"/><div className="absolute inset-[20%] rounded-full border border-white/10"/><div className="absolute inset-[33%] rounded-full border border-white/10"/><div className="absolute inset-[49%] rounded-full bg-[#ff5a00] shadow-[0_0_80px_rgba(255,90,0,.5)]"/><span className="absolute left-1/2 top-[5%] h-[90%] w-px origin-center -translate-x-1/2 rotate-[22deg] bg-gradient-to-b from-transparent via-[#ff5a00] to-transparent"/><span className="absolute left-[5%] top-1/2 h-px w-[90%] -translate-y-1/2 bg-white/10"/><span className="absolute left-[8%] top-[16%] font-mono-custom text-[8px] uppercase tracking-widest text-white/40">Social</span><span className="absolute bottom-[16%] right-[8%] font-mono-custom text-[8px] uppercase tracking-widest text-[#ff5a00]">Story</span></div>}
function Hero(){return <section className="relative min-h-[100svh] overflow-hidden bg-[#080908] px-5 pb-10 pt-[150px] text-[#f2eee5] md:px-10"><div className="hero-grid absolute inset-0 opacity-50"/><div className="hero-vignette absolute inset-0"/><div className="relative z-10 mx-auto flex min-h-[calc(100svh-190px)] max-w-[1600px] flex-col justify-between"><div className="font-mono-custom text-[9px] uppercase tracking-[.18em] text-white/45"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-[#ff5a00]"/> Social-first media / East Java</div><div className="grid items-center gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5a00]">01 / The story starts here</p><h1 className="mt-5 max-w-6xl font-display text-[clamp(4.2rem,10vw,10.5rem)] font-semibold leading-[.78] tracking-[-.065em]">Yang menarik,<br/><span className="text-[#ff5a00]">kami pajang.</span></h1><p className="mt-8 max-w-xl text-base leading-relaxed text-white/50 md:text-lg">Dari satu post, satu tempat, satu orang — kami mengikuti ceritanya sampai kamu ingin melihat lebih dekat.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/stories" className="bg-[#f2eee5] px-5 py-3 font-mono-custom text-[9px] uppercase text-black">Enter stories <ArrowDownRight className="ml-1 inline" size={13}/></Link><a href={INSTAGRAM} target="_blank" rel="noreferrer" className="border border-white/20 px-5 py-3 font-mono-custom text-[9px] uppercase">Instagram <Instagram className="ml-1 inline" size={12}/></a></div></div><div className="hidden lg:block"><Signal/></div></div><div className="flex items-end justify-between border-t border-white/10 pt-3 font-mono-custom text-[8px] uppercase tracking-widest text-white/35"><span>Scroll to continue the journey</span><span className="flex items-center gap-2">↓ <span className="hidden sm:inline">Keep moving</span></span></div></div></section>}
function Journey(){return <section className="bg-[#11110f] text-[#f2eee5]"><div className="mx-auto max-w-[1600px] px-5 md:px-10"><div className="grid lg:grid-cols-[.35fr_1.65fr]"><div className="hidden lg:block"><div className="sticky top-[100px] py-24"><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">02 / The journey</p><div className="mt-10 h-[420px] w-px bg-white/15"><div className="h-1/2 w-full bg-[#ff5a00]"/></div><p className="mt-5 max-w-[160px] font-mono-custom text-[8px] uppercase leading-relaxed text-white/35">Every scroll reveals another layer of the story.</p></div></div><div className="border-l border-white/10"><JourneyChapter number="02.1" title="Kami mulai dari yang bergerak." copy="Social media menangkap momen ketika ia sedang terjadi. Kami tidak ingin berhenti di sana." image="/editorial-portrait.jpg"/><JourneyChapter number="02.2" title="Lalu kami mendekat." copy="Orang, tempat, karya, dan kebiasaan mendapat ruang untuk bernapas — bukan sekadar thumbnail." image="/coastline.jpg" flip/><JourneyChapter number="02.3" title="Sampai ceritanya punya tempat tinggal." copy="Website menjadi arsip yang hidup: sebuah perjalanan dari scroll cepat menuju rasa ingin tahu yang lebih dalam." image="/studio-table.jpg"/></div></div></div></section>}
function JourneyChapter({number,title,copy,image,flip=false}:{number:string;title:string;copy:string;image:string;flip?:boolean}){return <article className={`grid min-h-[90svh] items-center gap-8 border-b border-white/10 py-20 md:py-28 lg:grid-cols-2 ${flip?'lg:[&>*:first-child]:order-2':''}`}><div className="relative overflow-hidden"><div className="absolute left-4 top-4 z-10 font-mono-custom text-[9px] text-white/45">{number}</div><img src={image} alt="" className="aspect-[4/5] w-full object-cover grayscale transition duration-1000 hover:grayscale-0" loading="lazy"/></div><div className="max-w-xl px-1 lg:px-10"><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5a00]">Majang Mejeng / Field note</p><h2 className="mt-6 font-display text-5xl font-semibold leading-[.88] md:text-7xl">{title}</h2><p className="mt-7 max-w-md text-base leading-relaxed text-white/45">{copy}</p><ArrowDownRight className="mt-10 text-[#ff5a00]" size={28}/></div></article>}
function MovingStories(){return <section className="bg-[#f2eee5] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1600px]"><div className="flex items-end justify-between gap-6"><div><p className="font-mono-custom text-[9px] uppercase tracking-widest text-[#ff5a00]">03 / What is moving</p><h2 className="mt-4 font-display text-6xl font-semibold leading-[.82] md:text-8xl">Yang sedang<br/>kami pajang.</h2></div><Link href="/stories" className="hidden font-mono-custom text-[9px] uppercase md:block">All stories <ArrowUpRight className="inline" size={13}/></Link></div><div className="mt-14 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><StoryCard story={stories[0]} large/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1">{stories.slice(1).map(s=><StoryCard key={s.slug} story={s}/>)}</div></div></div></section>}
function StoryCard({story,large=false}:{story:typeof stories[number];large?:boolean}){return <Link href={`/stories/${story.slug}`} onClick={()=>track('story_open',{slug:story.slug})} className="group block overflow-hidden border border-[#11110f] bg-[#f2eee5]"><div className={`relative overflow-hidden ${large?'aspect-[16/10]':'aspect-[16/9]'}`}><img src={story.image} alt={story.title} loading="lazy" className="h-full w-full object-cover transition duration-1000 group-hover:scale-105"/><span className="absolute left-4 top-4 bg-[#ff5a00] px-2 py-1 font-mono-custom text-[8px] uppercase">{story.category}</span><span className="absolute bottom-4 right-4 rounded-full bg-[#f2eee5] p-3"><ArrowUpRight size={15}/></span></div><div className="p-5 md:p-7"><div className="font-mono-custom text-[8px] uppercase text-black/40">{story.platform} · {story.read}</div><h3 className={`mt-3 font-display font-semibold leading-[.9] ${large?'text-4xl md:text-6xl':'text-2xl md:text-3xl'}`}>{story.title}</h3><p className="mt-4 max-w-2xl text-sm leading-relaxed text-black/50">{story.dek}</p></div></Link>}
function Worlds(){return <section className="bg-[#ff5a00] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1600px]"><div className="grid gap-10 lg:grid-cols-[.45fr_1.55fr]"><div><p className="font-mono-custom text-[9px] uppercase">04 / Worlds</p><p className="mt-5 max-w-xs text-sm leading-relaxed">Bukan kategori yang kaku. Ini enam pintu untuk menemukan hal berikutnya.</p></div><div className="grid border-l border-black/25">{worlds.map((w,i)=><Link key={w} href="/stories" className="group flex items-center justify-between border-b border-black/25 px-5 py-7 font-display text-4xl transition hover:bg-black hover:text-[#f2eee5] md:px-8 md:text-6xl"><span><span className="mr-4 font-mono-custom text-[9px] align-middle">0{i+1}</span>{w}</span><ArrowUpRight className="transition group-hover:translate-x-1 group-hover:-translate-y-1"/></Link>)}</div></div></div></section>}
function Proof(){return <section className="bg-[#11110f] px-5 py-24 text-[#f2eee5] md:px-10 md:py-32"><div className="mx-auto max-w-[1600px]"><div className="grid gap-14 lg:grid-cols-[.55fr_1.45fr]"><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">05 / The people</p><h2 className="mt-5 max-w-sm font-display text-5xl font-semibold leading-[.88] md:text-7xl">Stories are carried by people.</h2></div><div><div className="grid border-y border-white/15 md:grid-cols-3">{[['01','People','Faces behind the places.'],['02','Places','Corners worth slowing down for.'],['03','Ideas','Signals before they become trends.']].map(([n,t,d])=><div key={n} className="border-b border-white/15 p-7 md:border-b-0 md:border-r last:border-r-0"><span className="font-mono-custom text-[8px] text-[#ff5a00]">{n}</span><h3 className="mt-16 font-display text-3xl">{t}</h3><p className="mt-3 text-sm text-white/40">{d}</p></div>)}</div><div className="mt-20 grid gap-4 sm:grid-cols-3">{creators.map(c=><div key={c.name} className="border border-white/15 p-5"><div className="flex aspect-square items-end bg-[#1c1c19] p-5 font-display text-6xl text-[#ff5a00]">{c.mark}</div><p className="mt-4 font-display text-xl">{c.name}</p><p className="mt-1 font-mono-custom text-[8px] uppercase text-white/35">{c.role}</p></div>)}</div></div></div></div></section>}
function SocialLoop(){return <section className="bg-[#f2eee5] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1600px]"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">06 / From social to story</p><h2 className="mt-5 max-w-3xl font-display text-6xl font-semibold leading-[.82] md:text-8xl">Temukan kami di mana kamu scroll.</h2></div><div className="flex flex-col justify-end"><p className="max-w-md text-base leading-relaxed text-black/50">Instagram dan TikTok adalah pintu masuk. Website ini adalah tempat cerita itu tumbuh lebih panjang.</p><div className="mt-8 flex flex-wrap gap-3"><a href={INSTAGRAM} target="_blank" rel="noreferrer" className="border border-black px-5 py-3 font-mono-custom text-[9px] uppercase">Instagram ↗</a><a href={TIKTOK} target="_blank" rel="noreferrer" className="border border-black px-5 py-3 font-mono-custom text-[9px] uppercase">TikTok ↗</a></div></div></div><div className="mt-16 overflow-hidden border-y border-black py-6"><div className="marquee-track flex w-max gap-16 font-display text-5xl md:text-8xl"><span>MAJANG</span><span>MEJENG</span><span>MEDIA</span><span>MAJANG</span><span>MEJENG</span><span>MEDIA</span></div></div></div></section>}
function WorkWithUs(){const [sent,setSent]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true);track('form_submit',{form:'work_with_us'});}return <Shell><Meta title="Work with Majang Mejeng" description="Kolaborasi dengan Majang Mejeng Media."/><main className="pt-[72px]"><section className="bg-[#11110f] px-5 py-24 text-[#f2eee5] md:px-10 md:py-36"><div className="mx-auto max-w-[1600px]"><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">Work with us / 07</p><h1 className="mt-6 max-w-6xl font-display text-6xl font-semibold leading-[.8] md:text-[9rem]">Bawa cerita<br/><span className="text-[#ff5a00]">ke meja kami.</span></h1></div></section><section className="px-5 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-[1200px] gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">Start a project</p><p className="mt-5 text-sm leading-relaxed text-black/50">Campaign, event, brand story, creator collaboration, atau sesuatu yang belum punya nama.</p></div>{sent?<div className="border border-black p-8"><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">Received</p><h2 className="mt-4 font-display text-5xl">Brief masuk. Terima kasih.</h2><p className="mt-5 text-sm text-black/50">Kami sudah menerima permintaan kolaborasi kamu.</p></div>:<form onSubmit={submit} className="grid gap-6"><input required name="name" placeholder="Nama / Brand" className="border-b border-black bg-transparent px-0 py-4 font-display text-2xl outline-none"/><input required type="email" name="email" placeholder="Email" className="border-b border-black bg-transparent px-0 py-4 font-display text-2xl outline-none"/><textarea required name="brief" placeholder="Ceritakan singkat kebutuhanmu..." rows={5} className="resize-none border-b border-black bg-transparent px-0 py-4 font-display text-2xl outline-none"/><button type="submit" className="mt-4 w-fit bg-[#ff5a00] px-7 py-4 font-mono-custom text-[9px] uppercase">Kirim brief <ArrowUpRight className="inline" size={13}/></button></form>}</div></section></main></Shell>}
function Listing({kind}:{kind:string}){const title=kind==='Creators'?'Orang-orang yang membuat cerita bergerak.':kind==='Community'?'Ruang untuk orang yang ingin ikut bergerak.':kind==='Originals'?'Cerita orisinal, lebih panjang, lebih dekat.':'Semua cerita yang sedang kami pajang.';return <Shell><Meta title={`${kind} — Majang Mejeng`} description={title}/><main className="pt-[72px]"><section className="bg-[#11110f] px-5 py-24 text-[#f2eee5] md:px-10 md:py-36"><div className="mx-auto max-w-[1600px]"><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">{kind} / 08</p><h1 className="mt-6 max-w-6xl font-display text-6xl font-semibold leading-[.82] md:text-9xl">{title}</h1></div></section>{kind==='Stories'||kind==='Originals'?<section className="px-5 py-20 md:px-10"><div className="mx-auto grid max-w-[1600px] gap-5 lg:grid-cols-3">{stories.map(s=><StoryCard key={s.slug} story={s}/>)}</div></section>:<section className="px-5 py-20 md:px-10"><div className="mx-auto grid max-w-[1600px] gap-5 md:grid-cols-3">{creators.map(c=><div key={c.name} className="border border-black p-5"><div className="aspect-square bg-[#11110f] p-5 font-display text-8xl text-[#ff5a00]">{c.mark}</div><h2 className="mt-5 font-display text-3xl">{c.name}</h2><p className="mt-2 font-mono-custom text-[9px] uppercase text-black/45">{c.role}</p></div>)}</div></section>}</main></Shell>}
function StoryDetail({slug}:{slug:string}){const story=stories.find(s=>s.slug===slug);if(!story)return <NotFound/>;return <Shell><Meta title={`${story.title} — Majang Mejeng`} description={story.dek}/><main className="pt-[72px]"><section className="bg-[#11110f] px-5 py-20 text-[#f2eee5] md:px-10 md:py-28"><div className="mx-auto max-w-[1600px]"><Link href="/stories" className="font-mono-custom text-[9px] uppercase text-white/40">← Back to stories</Link><div className="mt-12 grid items-end gap-10 lg:grid-cols-[1.3fr_.7fr]"><h1 className="font-display text-6xl font-semibold leading-[.82] md:text-9xl">{story.title}</h1><p className="text-sm leading-relaxed text-white/45">{story.dek}</p></div></div></section><section className="px-5 py-10 md:px-10"><div className="mx-auto max-w-[1200px]"><img src={story.image} alt={story.title} className="aspect-[16/9] w-full object-cover"/><div className="mx-auto max-w-2xl py-14"><p className="font-mono-custom text-[9px] uppercase text-[#ff5a00]">{story.category} · {story.platform} · {story.read}</p><p className="mt-8 text-lg leading-[1.8]">Cerita ini berangkat dari percakapan kecil dan berkembang menjadi catatan tentang orang, tempat, dan hal-hal yang sering kita lewati terlalu cepat. Majang Mejeng mengajak kamu memperlambat scroll, melihat detail, lalu membawa cerita itu kembali ke dunia sehari-hari.</p><div className="mt-12 border-y border-black py-8"><Link href="/stories" className="font-mono-custom text-[9px] uppercase">Explore another story <ArrowRight className="inline" size={13}/></Link></div></div></div></section></main></Shell>}
function Home(){return <Shell><Meta title="Majang Mejeng — Yang menarik, kami pajang." description="Cerita, orang, tempat, budaya, dan momen dari Majang Mejeng Media."/><main><Hero/><Journey/><MovingStories/><Worlds/><Proof/><SocialLoop/><section className="bg-[#ff5a00] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1600px]"><p className="font-mono-custom text-[9px] uppercase">07 / Keep moving</p><h2 className="mt-5 max-w-6xl font-display text-6xl font-semibold leading-[.82] md:text-9xl">Ada cerita<br/>berikutnya.</h2><Link href="/work-with-us" className="mt-10 inline-block bg-[#11110f] px-6 py-4 font-mono-custom text-[9px] uppercase text-[#f2eee5]">Work with us <ArrowUpRight className="inline" size={13}/></Link></div></section></main></Shell>}
function AppRoutes(){return <WouterRouter base="/MAJANGMEJENG"><Switch><Route path="/" component={Home}/><Route path="/stories/:slug">{p=><StoryDetail slug={p.slug}/>}</Route><Route path="/stories"><Listing kind="Stories"/></Route><Route path="/originals"><Listing kind="Originals"/></Route><Route path="/creators"><Listing kind="Creators"/></Route><Route path="/community"><Listing kind="Community"/></Route><Route path="/work-with-us" component={WorkWithUs}/><Route path="/go/instagram"><a href={INSTAGRAM} target="_blank" rel="noreferrer">Instagram</a></Route><Route path="/go/tiktok"><a href={TIKTOK} target="_blank" rel="noreferrer">TikTok</a></Route><Route component={NotFound}/></Switch></WouterRouter>}
export default function App(){return <QueryClientProvider client={queryClient}><ErrorBoundary><TooltipProvider><AppRoutes/><Toaster/></TooltipProvider></ErrorBoundary></QueryClientProvider>}
