import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, ExternalLink, Instagram, Menu, Search, Share2, X } from 'lucide-react';
import { Link, Route, Switch, useLocation, Router } from 'wouter';
import logoAsset from '@assets/IMG_1920_1786731585196.png';

const logo=logoAsset, IG='https://www.instagram.com/majangmejeng_/', TT='https://www.tiktok.com/@majangmejeng_?lang=id-ID';
const MEDIA_BASE=import.meta.env.BASE_URL;
const img=[`${MEDIA_BASE}editorial-portrait.jpg`,`${MEDIA_BASE}coastline.jpg`,`${MEDIA_BASE}studio-table.jpg`];
type Story={slug:string;category:string;title:string;dek:string;image:string;read:string;date:string};
const stories:Story[]=[
{slug:'pasar-santa-dan-kota-yang-mendengar',category:'Places',title:'Di balik riuhnya pasar, ada kota yang sedang belajar mendengar',dek:'Ruang kecil, suara besar. Menyusuri tempat-tempat yang membuat sebuah kota terasa punya nadi.',image:img[0],read:'05 min',date:'12 Aug 2026'},
{slug:'mereka-yang-memilih-pulang',category:'People',title:'Mereka yang memilih pulang, lalu membuat rumahnya sendiri',dek:'Empat percakapan tentang pulang, tumbuh, dan keberanian untuk memulai lagi.',image:img[1],read:'04 min',date:'08 Aug 2026'},
{slug:'zine-stiker-dan-hal-kecil',category:'Creators',title:'Zine, stiker, dan hal-hal kecil yang menolak hilang',dek:'Catatan dari meja kerja para pembuat gambar yang menjaga ide tetap bergerak.',image:img[2],read:'06 min',date:'02 Aug 2026'},
{slug:'warung-kecil-cerita-besar',category:'Food',title:'Warung kecil, cerita besar, dan resep yang berpindah tangan',dek:'Tentang rasa yang bertahan karena orang-orang memilih untuk terus membuatnya.',image:img[1],read:'03 min',date:'29 Jul 2026'},
{slug:'malam-yang-mengumpulkan-orang',category:'Culture',title:'Malam yang mengumpulkan orang-orang yang biasanya berjalan sendiri',dek:'Ketika musik, ruang publik, dan percakapan menjadi alasan untuk bertemu.',image:img[0],read:'05 min',date:'22 Jul 2026'}];
const cats=['All','People','Places','Culture','Food','Ideas','Creators'];
function Meta({title}:{title:string}){useEffect(()=>{document.title=title},[title]);return null}
function Reveal({children,className='' }:{children:ReactNode;className?:string}){return <div className={'reveal '+className}>{children}</div>}
function useMotion(){useEffect(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const els=[...document.querySelectorAll<HTMLElement>('.reveal,.word,.motion-image,.counter')];if(reduce){els.forEach(e=>e.classList.add('on'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');io.unobserve(e.target)}}),{threshold:.1});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[])}
function Cursor(){const[p,setP]=useState({x:-100,y:-100});const[l,setL]=useState('');const[on,setOn]=useState(false);useEffect(()=>{const m=matchMedia('(pointer:fine)');setOn(m.matches);if(!m.matches)return;const move=(e:MouseEvent)=>setP({x:e.clientX,y:e.clientY});const over=(e:MouseEvent)=>setL((e.target as HTMLElement).closest<HTMLElement>('[data-cursor]')?.dataset.cursor||'');addEventListener('mousemove',move);document.addEventListener('mouseover',over);return()=>{removeEventListener('mousemove',move);document.removeEventListener('mouseover',over)}},[]);return on?<div className={'cursor '+(l?'hot':'')} style={{left:p.x,top:p.y}}>{l}</div>:null}
function Progress(){const[p,setP]=useState(0);useEffect(()=>{const f=()=>{const h=document.documentElement.scrollHeight-innerHeight;setP(h?scrollY/h:0)};addEventListener('scroll',f,{passive:true});f();return()=>removeEventListener('scroll',f)},[]);return <div className="progress"><span style={{transform:`scaleY(${p})`}}/><b>{Math.round(p*100).toString().padStart(3,'0')}</b></div>}
function Header(){const[menu,setMenu]=useState(false);const[search,setSearch]=useState(false);const[loc]=useLocation();return <><header className="header"><Link href="/" className="brand"><img src={logo} alt="Majang Mejeng"/><span>MAJANG<br/>MEJENG<br/>MEDIA</span></Link><nav>{[['Stories','/stories'],['Originals','/originals'],['People','/people'],['Culture','/culture']].map(([n,h],i)=><Link className={loc===h?'active':''} href={h} key={h}><small>0{i+1}</small>{n}</Link>)}</nav><div className="header-actions"><button aria-label="Search" onClick={()=>setSearch(true)}><Search size={17}/></button><Link className="header-work" href="/collaborate">Collaborate <ArrowUpRight size={12}/></Link><button aria-label="Menu" className="menu-button" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<MenuPanel close={()=>setMenu(false)}/>} {search&&<SearchPanel close={()=>setSearch(false)}/>}</>}
function MenuPanel({close}:{close:()=>void}){return <div className="menu-panel"><div className="menu-head"><span>MENU / 2026</span><button aria-label="Close menu" onClick={close}><X/></button></div>{[['Stories','/stories'],['Originals','/originals'],['People','/people'],['Places','/places'],['Culture','/culture'],['Creators','/creators'],['Community','/community'],['About','/about']].map(([n,h],i)=><Link key={h} href={h} onClick={close}><small>0{i+1}</small><strong>{n}</strong><ArrowUpRight/></Link>)}<div className="menu-social"><a href={IG} target="_blank" rel="noreferrer">Instagram <ExternalLink size={12}/></a><a href={TT} target="_blank" rel="noreferrer">TikTok <ExternalLink size={12}/></a></div></div>}
function SearchPanel({close}:{close:()=>void}){const[q,setQ]=useState('');const[cat,setCat]=useState('All');const found=useMemo(()=>stories.filter(s=>(cat==='All'||s.category===cat)&&`${s.title} ${s.dek}`.toLowerCase().includes(q.toLowerCase())),[q,cat]);return <div className="search-panel"><div className="search-card"><button aria-label="Close search" onClick={close}><X/></button><span className="eyebrow orange">SEARCH / MAJANG MEJENG</span><h2>Find what is moving.</h2><div className="search-input"><Search/><input autoFocus placeholder="Cari cerita, orang, tempat, ide..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="chips">{cats.map(c=><button className={cat===c?'selected':''} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div>{found.map(s=><Link onClick={close} className="search-result" key={s.slug} href={'/stories/'+s.slug}><small>{s.category} · {s.read}</small><strong>{s.title}</strong><ArrowUpRight/></Link>)}</div></div>}
function Footer(){return <footer><div className="footer-grid"><div><div className="footer-logo"><img src={logo} alt=""/><strong>MAJANG MEJENG</strong></div><p>Follow what is moving. Dari social menuju cerita yang lebih dalam.</p><div className="social"><a href={IG} target="_blank" rel="noreferrer">Instagram <ExternalLink size={12}/></a><a href={TT} target="_blank" rel="noreferrer">TikTok <ExternalLink size={12}/></a></div></div><div><span className="eyebrow">EXPLORE</span><Link href="/stories">Stories</Link><Link href="/originals">Originals</Link><Link href="/people">People</Link><Link href="/places">Places</Link><Link href="/culture">Culture</Link></div><div><span className="eyebrow">DISCOVER</span><Link href="/creators">Creators</Link><Link href="/community">Community</Link><Link href="/about">About</Link><Link href="/submit-story">Submit story</Link></div><div><span className="eyebrow">WORK WITH US</span><p>Campaign, editorial, event, creator partnership.</p><Link href="/collaborate">Kirim brief <ArrowUpRight/></Link></div></div><div className="footer-bottom"><span>MAJANG MEJENG MEDIA / INDONESIA</span><span>FOLLOW WHAT IS MOVING.</span><span>Privacy · Terms</span></div></footer>}
function Home(){useMotion();return <><Meta title="Majang Mejeng — Follow what is moving"/><main><Hero/><section className="statement light"><span className="eyebrow">02 / THE SIGNAL</span><Reveal><h2>Social menangkap <em>momen.</em><br/>Kami mencari <em>ceritanya.</em></h2><div className="two"><p>Instagram dan TikTok menangkap sinyal pertama. Majang Mejeng memberi konteks, wajah, tempat, dan waktu agar momen punya ruang untuk tinggal.</p><span>ONE POST → ONE QUESTION → ONE STORY</span></div></Reveal></section><Journey/><StoriesSection/><Worlds/><People/><Social/><FAQ/><CTA/></main></>}
function Hero(){return <section className="hero"><div className="hero-grid"/><div className="hero-meta"><span><i/> SOCIAL-FIRST MEDIA / INDONESIA</span><span>V6 / 2026</span></div><div className="hero-center"><Reveal className="hero-copy"><span className="eyebrow orange">01 / THE STORY STARTS HERE</span><h1><span className="word">Yang</span> <span className="word">menarik,</span><br/><em className="word">kami pajang.</em></h1><p>Dari satu post, satu tempat, satu orang — kami mengikuti ceritanya sampai kamu ingin melihat lebih dekat.</p><div className="hero-actions"><Link href="/stories" data-cursor="EXPLORE">Explore stories <ArrowDownRight/></Link><a href={IG} target="_blank" rel="noreferrer">Instagram <Instagram/></a></div></Reveal><div className="orb" data-cursor="DRAG"><i/><i/><i/><span/></div></div><button className="scroll" onClick={()=>document.getElementById('journey')?.scrollIntoView({behavior:'smooth'})}>SCROLL TO CONTINUE <ArrowDown/></button></section>}
function Journey(){return <section id="journey" className="journey dark"><aside><span className="eyebrow">03 / THE JOURNEY</span><div className="rail"/><span>EVERY SCROLL REVEALS ANOTHER LAYER.</span></aside><div>{[['03.1','Mulai dari yang bergerak.',img[0]],['03.2','Lalu kami mendekat.',img[1]],['03.3','Sampai ceritanya punya tempat tinggal.',img[2]]].map(([n,t,p],i)=><article className="scene" key={n}><div className="motion-image" data-cursor="VIEW"><span>{n}</span><img src={p} alt=""/></div><Reveal><small className="orange">FIELD NOTE / {n}</small><h2>{t}</h2><p>{i===0?'Social menangkap momen ketika ia sedang terjadi. Kami mengikuti sinyalnya.':i===1?'Orang, tempat, karya, dan kebiasaan mendapat ruang untuk bernapas — bukan sekadar thumbnail.':'Website menjadi arsip yang hidup: perjalanan dari scroll cepat menuju rasa ingin tahu yang lebih dalam.'}</p></Reveal></article>)}</div></section>}
function StoriesSection(){return <section className="stories light"><div className="section-head"><span className="eyebrow">04 / WHAT'S MOVING</span><Link href="/stories">View all <ArrowUpRight/></Link></div><Link className="feature" href={'/stories/'+stories[0].slug} data-cursor="READ"><div className="motion-image"><img src={stories[0].image} alt=""/><span>{stories[0].category}</span></div><Reveal><small className="orange">FEATURED STORY</small><h2>{stories[0].title}</h2><p>{stories[0].dek}</p><b>Read story <ArrowUpRight/></b></Reveal></Link><div className="story-list">{stories.slice(1).map((s,i)=><Link href={'/stories/'+s.slug} key={s.slug}><small>0{i+1}</small><strong>{s.title}</strong><span>{s.category}</span><ArrowUpRight/></Link>)}</div></section>}
function Worlds(){return <section className="worlds light"><Reveal><span className="eyebrow">05 / THE WORLDS</span><h2>Different <em>worlds.</em><br/>One signal.</h2><p>People, Places, Culture, Food, Ideas, Creators — taxonomy yang dibuat untuk terus tumbuh.</p></Reveal><div>{['People','Places','Culture','Food','Ideas','Creators'].map((w,i)=><Link key={w} href={'/'+w.toLowerCase()} data-cursor="EXPLORE"><small>0{i+1}</small><strong>{w}</strong><ArrowUpRight/></Link>)}</div></section>}
function People(){const[i,setI]=useState(0);const c=[['Rara Sekar','Musisi','Yogyakarta',img[0]],['Jalu Kancana','Fotografer','Bandung',img[1]],['Nana Kautsar','Perupa','Makassar',img[2]]][i];return <section className="people dark"><div className="people-head"><Reveal><span className="eyebrow">06 / THE PEOPLE</span><h2>Behind every <em>story</em><br/>is a person.</h2></Reveal><p>Creator, artist, entrepreneur, community leader. Kami mengikuti orang-orang yang membuat sebuah tempat terasa hidup.</p></div><div className="people-stage"><div className="motion-image"><img key={c[0]} src={c[3]} alt={c[0]}/><span>0{i+1} / 03</span></div><div><small className="orange">CREATOR PROFILE</small><h3>{c[0]}</h3><p>{c[1]} · {c[2]}</p><Link href="/creators">Explore creators <ArrowUpRight/></Link><div className="controls"><button aria-label="Previous creator" onClick={()=>setI((i+2)%3)}><ArrowLeft/></button><button aria-label="Next creator" onClick={()=>setI((i+1)%3)}><ArrowRight/></button></div></div></div></section>}
function Social(){return <section className="social-section orange-bg"><Reveal><span className="eyebrow">07 / THE SOCIAL CURRENT</span><h2>From social<br/><em>to story.</em></h2><p>Social adalah tempat sinyal pertama muncul. Website adalah tempat cerita itu tinggal.</p></Reveal><div className="social-cards"><a href={IG} target="_blank" rel="noreferrer" data-cursor="INSTAGRAM"><span>INSTAGRAM</span><strong>@majangmejeng_</strong><ArrowUpRight/></a><a href={TT} target="_blank" rel="noreferrer" data-cursor="TIKTOK"><span>TIKTOK</span><strong>@majangmejeng_</strong><ArrowUpRight/></a></div></section>}
function FAQ(){const[o,setO]=useState<number|null>(null);return <section className="faq light"><div><span className="eyebrow">08 / FAQ</span><h2>Questions,<br/><em>answered.</em></h2></div><div>{[['Apa itu Majang Mejeng?','Media social-first yang memperpanjang sinyal menjadi cerita.'],['Apa yang kalian liput?','People, Places, Culture, Food, Ideas, dan Creators.'],['Bagaimana mengirim cerita?','Gunakan Submit Story dan kirim konteks awalnya.'],['Apakah menerima creator baru?','Ya, melalui open call, discovery, atau collaboration.'],['Bagaimana brand bekerja sama?','Campaign, event, editorial, creator partnership, dan media placement.']].map(([q,a],i)=><div className={'faq-row '+(o===i?'open':'')} key={q}><button onClick={()=>setO(o===i?null:i)}><strong>{q}</strong><ChevronDown/></button><div><p>{a}</p></div></div>)}</div></section>}
function CTA(){return <section className="cta"><span className="eyebrow">09 / WORK WITH US</span><h2>Punya sesuatu<br/><em>yang menarik?</em></h2><p>Campaign, editorial, event, creator partnership, atau cerita yang belum menemukan tempat.</p><Link href="/collaborate" data-cursor="START">Start a collaboration <ArrowUpRight/></Link></section>}
function Archive(){useMotion();return <Page title="Stories" kicker="STORY ARCHIVE"><div className="archive-grid">{stories.map((s,i)=><Link href={'/stories/'+s.slug} className="archive-card" key={s.slug} data-cursor="READ"><div className="motion-image"><img src={s.image} alt=""/><span>0{i+1}</span></div><small>{s.category} · {s.date} · {s.read}</small><h2>{s.title}</h2><p>{s.dek}</p></Link>)}</div></Page>}
function Story({slug}:{slug:string}){const s=stories.find(x=>x.slug===slug)||stories[0];useMotion();return <main className="story"><section className="story-hero"><Reveal><small className="orange">{s.category} / {s.date}</small><h1>{s.title}</h1><p>{s.dek}</p></Reveal><div className="motion-image"><img src={s.image} alt=""/></div></section><article><div className="story-toolbar"><span>READING STORY</span><button aria-label="Share story" onClick={()=>navigator.share?.({title:s.title,url:location.href})}><Share2/> Share</button></div><p className="lead">{s.dek} Ini adalah ruang editorial untuk membawa momen lebih dekat dan melihat orang di baliknya.</p><img src={img[1]} alt=""/><p>Kami percaya cerita lokal tidak harus keras untuk menjadi penting. Ia hadir dalam kebiasaan, suara, ruang, dan orang yang memilih tetap membuat sesuatu.</p><img src={img[2]} alt=""/><p>Setiap detail memberi lapisan. Website menjadi tempat untuk membaca pelan, lalu kembali menemukan cerita berikutnya.</p><Link className="next" href={'/stories/'+stories[(stories.findIndex(x=>x.slug===s.slug)+1)%stories.length].slug}>Next story <ArrowUpRight/></Link></article></main>}
function Page({title,kicker,children}:{title:string;kicker:string;children:ReactNode}){useMotion();return <main className="page"><section className="inner-hero"><span className="eyebrow orange">{kicker}</span><h1>{title}</h1></section>{children}</main>}
function Generic({title,kicker,items}:{title:string;kicker:string;items:string[]}){return <Page title={title} kicker={kicker}><div className="generic-list">{items.map((x,i)=><Link href="/stories" key={x}><small>0{i+1}</small><strong>{x}</strong><ArrowUpRight/></Link>)}</div></Page>}
function FormPage(){const[done,setDone]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(e.currentTarget.checkValidity())setDone(true);else e.currentTarget.reportValidity()};return <Page title="Let's make something move." kicker="WORK WITH US"><div className="form-layout">{done?<div className="success"><span className="eyebrow orange">RECEIVED</span><h2>Terima kasih. Ceritanya sudah masuk.</h2><p>Tim Majang Mejeng akan meninjau brief ini dan menghubungi kamu.</p><Link href="/">Back home <ArrowUpRight/></Link></div>:<form onSubmit={submit}><label>Nama lengkap<input required placeholder="Nama lengkap"/></label><label>Email<input required type="email" placeholder="email@contoh.com"/></label><label>Jenis kerja sama<select required defaultValue=""><option value="" disabled>Pilih kebutuhan</option><option>Campaign</option><option>Editorial</option><option>Event</option><option>Creator partnership</option></select></label><label>Konteks brief<textarea required placeholder="Tulis konteks, tujuan, timeline, dan hal penting lainnya..."/></label><button>Kirim brief <ArrowUpRight/></button></form>}</div></Page>}
function App(){return <Router base="/MAJANGMEJENG"><div className="app"><Header/><Progress/><Cursor/><Switch><Route path="/"><Home/></Route><Route path="/stories/:slug">{p=><Story slug={p.slug}/>}</Route><Route path="/stories" component={Archive}/><Route path="/originals">{()=> <Generic title="Originals" kicker="ORIGINALS" items={['Video','Documentary','Mini Series','Photo Essay','Special Projects']}/>}</Route><Route path="/creators">{()=> <Generic title="Creators" kicker="CREATORS" items={['Artists','Photographers','Musicians','Filmmakers','People to watch']}/>}</Route><Route path="/people">{()=> <Generic title="People" kicker="PEOPLE" items={['Creators','Artists','Entrepreneurs','Community leaders']}/>}</Route><Route path="/places">{()=> <Generic title="Places" kicker="PLACES" items={['Cities','Hidden places','Food spots','Local guides']}/>}</Route><Route path="/culture">{()=> <Generic title="Culture" kicker="CULTURE" items={['Local culture','Events','Youth culture','Traditions']}/>}</Route><Route path="/community">{()=> <Generic title="Community" kicker="COMMUNITY" items={['Open call','Submit story','Events','Community projects']}/>}</Route><Route path="/about">{()=> <Generic title="About Majang Mejeng" kicker="ABOUT" items={['Who we are','Editorial philosophy','Our values','Our people']}/>}</Route><Route path="/submit-story"><FormPage/></Route><Route path="/collaborate"><FormPage/></Route><Route><Generic title="404" kicker="NOT FOUND" items={['Return home']}/></Route></Switch><Footer/></div></Router>}
export default App;
