import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDown, ArrowUpRight, ChevronDown, ExternalLink, Instagram, Menu, Search, X } from 'lucide-react';
import { Link, Route, Switch, Router, useLocation } from 'wouter';
import logo from '@assets/IMG_1920_1786731585196.png';
import './v8.css';

const BASE = import.meta.env.BASE_URL;
const IG = 'https://www.instagram.com/majangmejeng_/';
const TT = 'https://www.tiktok.com/@majangmejeng_?lang=id-ID';
const media = [`${BASE}editorial-portrait.jpg`, `${BASE}coastline.jpg`, `${BASE}studio-table.jpg`];

type Story = { slug:string; category:string; title:string; dek:string; image:string; read:string; date:string };
const stories: Story[] = [
  {slug:'pasar-santa-dan-kota-yang-mendengar',category:'Places',title:'Di balik riuhnya pasar, ada kota yang sedang belajar mendengar',dek:'Ruang kecil, suara besar. Menyusuri tempat-tempat yang membuat sebuah kota terasa punya nadi.',image:media[0],read:'05 min',date:'12 Aug 2026'},
  {slug:'mereka-yang-memilih-pulang',category:'People',title:'Mereka yang memilih pulang, lalu membuat rumahnya sendiri',dek:'Empat percakapan tentang pulang, tumbuh, dan keberanian untuk memulai lagi.',image:media[1],read:'04 min',date:'08 Aug 2026'},
  {slug:'zine-stiker-dan-hal-kecil',category:'Creators',title:'Zine, stiker, dan hal-hal kecil yang menolak hilang',dek:'Catatan dari meja kerja para pembuat gambar yang menjaga ide tetap bergerak.',image:media[2],read:'06 min',date:'02 Aug 2026'},
  {slug:'warung-kecil-cerita-besar',category:'Food',title:'Warung kecil, cerita besar, dan resep yang berpindah tangan',dek:'Tentang rasa yang bertahan karena orang-orang memilih untuk terus membuatnya.',image:media[1],read:'03 min',date:'29 Jul 2026'},
  {slug:'malam-yang-mengumpulkan-orang',category:'Culture',title:'Malam yang mengumpulkan orang-orang yang biasanya berjalan sendiri',dek:'Ketika musik, ruang publik, dan percakapan menjadi alasan untuk bertemu.',image:media[0],read:'05 min',date:'22 Jul 2026'}
];
const cats = ['All','People','Places','Culture','Food','Ideas','Creators'];

function Reveal({children,className='' }:{children:ReactNode;className?:string}) { return <div className={`v8-reveal ${className}`}>{children}</div>; }
function useReveal() { useEffect(()=>{ const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches; const els=[...document.querySelectorAll<HTMLElement>('.v8-reveal,.v8-node,.v8-media')]; if(reduce){els.forEach(x=>x.classList.add('is-in'));return;} const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-in');io.unobserve(e.target)}}),{threshold:.12}); els.forEach(x=>io.observe(x)); return()=>io.disconnect(); },[]); }
function Meta({title}:{title:string}){useEffect(()=>{document.title=title},[title]);return null;}

function Header(){const [menu,setMenu]=useState(false);const [search,setSearch]=useState(false);const [loc]=useLocation(); return <>
  <header className="v8-header"><Link href="/" className="v8-brand"><img src={logo} alt="Majang Mejeng"/><span>MAJANG<br/>MEJENG<br/>MEDIA</span></Link>
    <nav>{[['Stories','/stories'],['Originals','/originals'],['People','/people'],['Culture','/culture']].map(([n,h],i)=><Link key={h} className={loc===h?'active':''} href={h}><small>0{i+1}</small>{n}</Link>)}</nav>
    <div className="v8-actions"><button aria-label="Search" onClick={()=>setSearch(true)}><Search size={17}/></button><Link className="v8-collab" href="/collaborate">Collaborate <ArrowUpRight size={13}/></Link><button aria-label={menu?'Close menu':'Menu'} onClick={()=>setMenu(!menu)}><Menu/></button></div>
  </header>
  {menu&&<div className="v8-overlay"><button aria-label="Close menu" className="v8-close" onClick={()=>setMenu(false)}><X/></button><span className="v8-eyebrow">MENU / 2026</span>{[['Stories','/stories'],['Originals','/originals'],['People','/people'],['Places','/places'],['Culture','/culture'],['Creators','/creators'],['Community','/community'],['About','/about']].map(([n,h],i)=><Link onClick={()=>setMenu(false)} key={h} href={h}><small>0{i+1}</small><strong>{n}</strong><ArrowUpRight/></Link>)}<div className="v8-social"><a href={IG} target="_blank" rel="noreferrer">Instagram <ExternalLink size={13}/></a><a href={TT} target="_blank" rel="noreferrer">TikTok <ExternalLink size={13}/></a></div></div>}
  {search&&<SearchPanel close={()=>setSearch(false)}/>}</>}

function SearchPanel({close}:{close:()=>void}){const[q,setQ]=useState('');const[cat,setCat]=useState('All');const found=useMemo(()=>stories.filter(s=>(cat==='All'||s.category===cat)&&`${s.title} ${s.dek}`.toLowerCase().includes(q.toLowerCase())),[q,cat]);return <div className="v8-search"><div className="v8-search-card"><button aria-label="Close search" onClick={close}><X/></button><span className="v8-eyebrow">SEARCH / MAJANG MEJENG</span><h2>Find what is moving.</h2><div className="v8-search-input"><Search/><input autoFocus placeholder="Cari cerita, orang, tempat, ide..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="v8-chips">{cats.map(c=><button className={cat===c?'selected':''} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div>{found.length?found.map(s=><Link onClick={close} href={`/stories/${s.slug}`} className="v8-result" key={s.slug}><small>{s.category} · {s.read}</small><strong>{s.title}</strong><ArrowUpRight/></Link>):<p className="v8-empty">Tidak ada cerita yang cocok.</p>}</div></div>}

function SignalNetwork(){const nodes=[['People',18,25],['Places',45,16],['Culture',74,30],['Food',32,54],['Creators',62,58],['Ideas',84,73]];return <div className="v8-network" aria-label="Majang Mejeng story signal network"><svg viewBox="0 0 100 100" aria-hidden="true"><path d="M18 25 L45 16 L74 30 L62 58 L84 73 M45 16 L32 54 L62 58 M32 54 L18 25"/></svg>{nodes.map(([name,x,y],i)=><Link key={String(name)} href={`/stories/${stories[i%stories.length].slug}`} className="v8-node" style={{left:`${x}%`,top:`${y}%`}}><span>{name}</span></Link>)}<div className="v8-core">MM<br/><b>SIGNAL</b></div></div>}

function Hero(){return <section className="v8-hero"><div className="v8-grid"/><div className="v8-meta"><span><i/> SOCIAL-FIRST MEDIA / INDONESIA</span><span>V8 / 2026</span></div><div className="v8-hero-copy"><Reveal><span className="v8-eyebrow">01 / THE STORY STARTS HERE</span><h1>FOLLOW<br/><em>WHAT IS MOVING.</em></h1><p>Majang Mejeng menemukan signal dari social, lalu membawanya lebih dekat menjadi cerita, manusia, tempat, dan budaya.</p><div className="v8-hero-links"><Link href="/stories">Explore stories <ArrowUpRight/></Link><a href={IG} target="_blank" rel="noreferrer">Instagram <Instagram/></a></div></Reveal></div><SignalNetwork/><button className="v8-scroll" onClick={()=>document.getElementById('signal')?.scrollIntoView({behavior:'smooth'})}>SCROLL TO CONTINUE <ArrowDown/></button></section>}

function Signal(){return <section id="signal" className="v8-section v8-dark"><div className="v8-side"><span className="v8-eyebrow">02 / LIVING SIGNAL</span><span>ONE SIGNAL → ONE QUESTION → ONE STORY</span></div><div className="v8-signal-copy"><Reveal><h2>Social menangkap <em>momen.</em><br/>Kami mencari <em>ceritanya.</em></h2><p>Network ini bukan dekorasi. Setiap titik adalah pintu menuju cerita. Setiap garis menunjukkan hubungan yang bisa ditelusuri.</p></Reveal><SignalNetwork/></div></section>}

function Wall(){return <section className="v8-section v8-wall"><div className="v8-section-head"><span className="v8-eyebrow">03 / LIVING STORY WALL</span><Link href="/stories">View archive <ArrowUpRight/></Link></div><div className="v8-wall-grid">{stories.slice(0,4).map((s,i)=><Link className={`v8-card card-${i}`} href={`/stories/${s.slug}`} key={s.slug}><div className="v8-media"><img src={s.image} alt=""/><span>{s.category}</span></div><small>{s.date} · {s.read}</small><h3>{s.title}</h3><p>{s.dek}</p></Link>)}</div></section>}

function Worlds(){return <section className="v8-section v8-dark v8-worlds"><Reveal><span className="v8-eyebrow">04 / EDITORIAL WORLDS</span><h2>Different <em>worlds.</em><br/>One signal.</h2><p>Taxonomy editorial yang bisa tumbuh mengikuti cerita: People, Places, Culture, Food, Ideas, Creators.</p></Reveal><div className="v8-world-list">{['People','Places','Culture','Food','Ideas','Creators'].map((w,i)=><Link href={`/${w.toLowerCase()}`} key={w}><small>0{i+1}</small><strong>{w}</strong><ArrowUpRight/></Link>)}</div></section>}

function SocialCurrent(){return <section className="v8-section v8-orange"><Reveal><span className="v8-eyebrow">05 / SOCIAL CURRENT</span><h2>FROM SOCIAL<br/><em>TO STORY.</em></h2><p>Instagram dan TikTok adalah tempat signal pertama muncul. Website menjadi ruang untuk membaca lebih pelan.</p></Reveal><div className="v8-social-grid"><a href={IG} target="_blank" rel="noreferrer"><span>INSTAGRAM</span><strong>@majangmejeng_</strong><ArrowUpRight/></a><a href={TT} target="_blank" rel="noreferrer"><span>TIKTOK</span><strong>@majangmejeng_</strong><ArrowUpRight/></a></div></section>}

function Collaboration(){const[done,setDone]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(e.currentTarget.checkValidity())setDone(true);else e.currentTarget.reportValidity()};return <Page title="Make something move." kicker="06 / COLLABORATE">{done?<div className="v8-success"><span className="v8-eyebrow">RECEIVED</span><h2>Brief sudah masuk.</h2><p>Terima kasih. Tim Majang Mejeng dapat meninjau kebutuhanmu dari form ini.</p><Link href="/">Back home <ArrowUpRight/></Link></div>:<form className="v8-form" onSubmit={submit}><label>Nama<input required name="name"/></label><label>Email<input required type="email" name="email"/></label><label>Kebutuhan<select required defaultValue="" name="type"><option value="" disabled>Pilih kebutuhan</option><option>Campaign</option><option>Editorial</option><option>Event</option><option>Creator partnership</option></select></label><label>Brief<textarea required name="brief" placeholder="Tujuan, timeline, konteks, dan hal penting lainnya..."/></label><button>Kirim brief <ArrowUpRight/></button></form>}</Page>}
function Archive(){return <Page title="Stories" kicker="STORY ARCHIVE"><div className="v8-archive">{stories.map((s,i)=><Link className="v8-archive-card" href={`/stories/${s.slug}`} key={s.slug}><div className="v8-media"><img src={s.image} alt=""/><span>0{i+1}</span></div><small>{s.category} · {s.date} · {s.read}</small><h2>{s.title}</h2><p>{s.dek}</p></Link>)}</div></Page>}
function Story({slug}:{slug:string}){const s=stories.find(x=>x.slug===slug)||stories[0];return <main className="v8-story"><section className="v8-story-hero"><Reveal><span className="v8-eyebrow">{s.category} / {s.date}</span><h1>{s.title}</h1><p>{s.dek}</p></Reveal><div className="v8-media"><img src={s.image} alt=""/></div></section><article><div className="v8-reading"><span>READING STORY / {s.read}</span><button onClick={()=>navigator.share?.({title:s.title,url:location.href})}>Share <ArrowUpRight/></button></div><p className="lead">{s.dek} Ini adalah ruang editorial untuk membawa signal lebih dekat dan melihat konteks di baliknya.</p><img src={media[1]} alt=""/><p>Kami percaya cerita lokal tidak harus keras untuk menjadi penting. Ia hadir dalam kebiasaan, suara, ruang, dan orang yang memilih terus membuat sesuatu.</p><img src={media[2]} alt=""/><p>Setiap detail memberi lapisan. Website menjadi tempat untuk membaca pelan, lalu kembali menemukan cerita berikutnya.</p><Link className="v8-next" href={`/stories/${stories[(stories.findIndex(x=>x.slug===s.slug)+1)%stories.length].slug}`}>Next story <ArrowUpRight/></Link></article></main>}
function Page({title,kicker,children}:{title:string;kicker:string;children:ReactNode}){useReveal();return <main className="v8-page"><section className="v8-inner-hero"><span className="v8-eyebrow">{kicker}</span><h1>{title}</h1></section>{children}</main>}
function Generic({title,kicker,items}:{title:string;kicker:string;items:string[]}){return <Page title={title} kicker={kicker}><div className="v8-generic">{items.map((x,i)=><Link href="/stories" key={x}><small>0{i+1}</small><strong>{x}</strong><ArrowUpRight/></Link>)}</div></Page>}
function Footer(){return <footer className="v8-footer"><div><img src={logo} alt=""/><h3>MAJANG MEJENG</h3><p>Follow what is moving. Dari social menuju cerita yang lebih dalam.</p><div className="v8-footer-social"><a href={IG} target="_blank" rel="noreferrer">Instagram</a><a href={TT} target="_blank" rel="noreferrer">TikTok</a></div></div><div><span>EXPLORE</span><Link href="/stories">Stories</Link><Link href="/originals">Originals</Link><Link href="/people">People</Link><Link href="/culture">Culture</Link></div><div><span>DISCOVER</span><Link href="/creators">Creators</Link><Link href="/community">Community</Link><Link href="/about">About</Link></div><div><span>WORK WITH US</span><Link href="/collaborate">Kirim brief <ArrowUpRight/></Link></div><div className="v8-footer-bottom">MAJANG MEJENG MEDIA / INDONESIA <b>FOLLOW WHAT IS MOVING.</b></div></footer>}

function Home(){useReveal();return <><Meta title="Majang Mejeng — Follow what is moving"/><main><Hero/><Signal/><Wall/><Worlds/><SocialCurrent/><section className="v8-cta"><span className="v8-eyebrow">07 / COLLABORATE</span><h2>Punya sesuatu<br/><em>yang menarik?</em></h2><p>Campaign, editorial, event, creator partnership, atau cerita yang belum menemukan tempat.</p><Link href="/collaborate">Start a collaboration <ArrowUpRight/></Link></section></main></>}
function App(){return <Router base="/MAJANGMEJENG"><div className="v8-app"><Header/><Switch><Route path="/"><Home/></Route><Route path="/stories/:slug">{p=><Story slug={p.slug}/>}</Route><Route path="/stories" component={Archive}/><Route path="/collaborate"><Collaboration/></Route><Route path="/submit-story"><Collaboration/></Route><Route path="/originals">{()=> <Generic title="Originals" kicker="ORIGINALS" items={['Video','Documentary','Mini Series','Photo Essay','Special Projects']}/>}</Route><Route path="/creators">{()=> <Generic title="Creators" kicker="CREATORS" items={['Artists','Photographers','Musicians','Filmmakers','People to watch']}/>}</Route><Route path="/people">{()=> <Generic title="People" kicker="PEOPLE" items={['Creators','Artists','Entrepreneurs','Community leaders']}/>}</Route><Route path="/places">{()=> <Generic title="Places" kicker="PLACES" items={['Cities','Hidden places','Food spots','Local guides']}/>}</Route><Route path="/culture">{()=> <Generic title="Culture" kicker="CULTURE" items={['Local culture','Events','Youth culture','Traditions']}/>}</Route><Route path="/community">{()=> <Generic title="Community" kicker="COMMUNITY" items={['Open call','Submit story','Events','Community projects']}/>}</Route><Route path="/about">{()=> <Generic title="About Majang Mejeng" kicker="ABOUT" items={['Who we are','Editorial philosophy','Our values','Our people']}/>}</Route><Route><Generic title="404" kicker="NOT FOUND" items={['Return home']}/></Route></Switch><Footer/></div></Router>}
export default App;
